apiVersion: v1
kind: Service
metadata:
  name: sctp-lb1
  annotations:
    loxilb.io/num-secondary-networks: "2"
    loxilb.io/lbmode: "fullnat"
    loxilb.io/liveness: "yes"
spec:
  externalTrafficPolicy: Local
  loadBalancerClass: loxilb.io/loxilb
  selector:
    what: sctp-test
  ports:
    - port: 55003
      protocol: SCTP
      targetPort: 9999
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: sctp-test
  labels:
    what: sctp-test
spec:
  tolerations:
  - key: "node.kubernetes.io/disk-pressure"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
    - name: sctp-test
      image: loxilbio/sctp-darn:latest
      imagePullPolicy: Always
      #command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 6 ; done"]
      command: ["sctp_darn","-H", "0.0.0.0","-P", "9999", "-l"]
      ports:
        - containerPort: 9999
