# -*- mode: ruby -*-
# vi: set ft=ruby :

#box_name = (ENV['VAGRANT_BOX'] || "ubuntu/focal64")
box_name = (ENV['VAGRANT_BOX'] || "sysnet4admin/Ubuntu-k8s")
box_version = "0.7.1"
Vagrant.configure("2") do |config|
  config.vm.box = "#{box_name}"
  config.vm.box_version = "#{box_version}"

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.define "bastion" do |bastion|
    bastion.vm.hostname = 'bastion'
    #bastion.vm.network :private_network, ip: "4.0.5.3", :netmask => "255.255.255.0"
    bastion.vm.network :private_network, ip: "4.0.4.3", :netmask => "255.255.255.0"
    bastion.vm.provision :shell, :path => "bastion.sh"
    bastion.vm.provider :virtualbox do |vbox|
        vbox.customize ["modifyvm", :id, "--memory", 8196]
        vbox.customize ["modifyvm", :id, "--cpus", 12]
        #vbox.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
        #vbox.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
    end
  end
end
