apiVersion: v1
kind: Service
metadata:
  name: nginx-lb1-ipv6
  annotations:
   # If there is a need to do liveness check from loxilb
   loxilb.io/liveness: "no"
   # Specify LB mode - one of default, onearm or fullnat
   loxilb.io/lbmode: "default"
   # Specify loxilb IPAM mode - one of ipv4, ipv6 or ipv6to4
   loxilb.io/ipam: "ipv6"
spec:
  externalTrafficPolicy: Local
  loadBalancerClass: loxilb.io/loxilb
  selector:
    what: nginx-test-ipv6
  ports:
    - port: 55002
      targetPort: 80 
  type: LoadBalancer
  ipFamilies:
    - IPv6
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-test-ipv6
  labels:
    what: nginx-test-ipv6
spec:
  containers:
    - name: nginx-test-ipv6
      image: nginx:stable
      ports:
        - containerPort: 80
