# -*- mode: ruby -*-
# vi: set ft=ruby :

k3snodes = (ENV['K8SNodes'] || "1").to_i
box_name = (ENV['VAGRANT_BOX'] || "sysnet4admin/Ubuntu-k8s")
box_version = "0.7.1"
Vagrant.configure("2") do |config|
  config.vm.box = "#{box_name}"
  config.vm.box_version = "#{box_version}"

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  (1..k3snodes).each do |node_number|
    config.vm.define "k0s-node#{node_number}" do |node|
      node.vm.hostname = "k0s-node#{node_number}"
      ip = node_number + 1
      node.vm.network :private_network, ip: "192.168.82.#{ip}", :netmask => "255.255.255.0"
      node.vm.provision :shell, :path => "k0s-install.sh"
      node.vm.provider :virtualbox do |vbox|
        vbox.customize ["modifyvm", :id, "--memory", 16000]
        vbox.customize ["modifyvm", :id, "--cpus", 8]
        vbox.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      end
    end
  end
end
