// Code generated by go-swagger; DO NOT EDIT.

package metadata

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetMetaOKCode is the HTTP code returned for type GetMetaOK
const GetMetaOKCode int = 200

/*
GetMetaOK Successfully retrieved metadata

swagger:response getMetaOK
*/
type GetMetaOK struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewGetMetaOK creates GetMetaOK with default headers values
func NewGetMetaOK() *GetMetaOK {

	return &GetMetaOK{}
}

// WithPayload adds the payload to the get meta o k response
func (o *GetMetaOK) WithPayload(payload interface{}) *GetMetaOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get meta o k response
func (o *GetMetaOK) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMetaOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetMetaInternalServerErrorCode is the HTTP code returned for type GetMetaInternalServerError
const GetMetaInternalServerErrorCode int = 500

/*
GetMetaInternalServerError Internal Server Error

swagger:response getMetaInternalServerError
*/
type GetMetaInternalServerError struct {
}

// NewGetMetaInternalServerError creates GetMetaInternalServerError with default headers values
func NewGetMetaInternalServerError() *GetMetaInternalServerError {

	return &GetMetaInternalServerError{}
}

// WriteResponse to the client
func (o *GetMetaInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
