// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Loxilb Rest API
//
//	Loxilb REST API for Baremetal Scenarios
//	Schemes:
//	  http
//	  https
//	Host: 0.0.0.0:11111
//	BasePath: /netlox/v1
//	Version: 0.0.1
//
//	Consumes:
//	  - application/json
//	  - multipart/form-data
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
