global:
  config:
    as: 64512
    router-id: 192.168.58.111
  apply-policy:
    config:
      export-policy-list:
        - set-next-hop-self
        - drop-vip
        - set-next-hop-vip
neighbors:
    - config:
        neighbor-address: 192.168.59.211
        peer-as: 64512
    - config:
        neighbor-address: 192.168.59.212
        peer-as: 64512
    - config:
        neighbor-address: 192.168.59.213
        peer-as: 64512
    - config:
        neighbor-address: 192.168.59.214
        peer-as: 64512
    - config:
        neighbor-address: 192.168.58.2
        peer-as: 65001
defined-sets:
    prefix-sets:
      prefix-set-name: vip
      prefix-list:
          - ip-prefix: 192.168.58.150/32
    neighbor-sets:
      - neighbor-set-name: ext
        neighbor-info-list: 
            - 192.168.58.2
      - neighbor-set-name: int
        neighbor-info-list:
            - 192.168.59.211
            - 192.168.59.212
            - 192.168.59.213
            - 192.168.59.214
policy-definitions:
   - name: set-next-hop-self
     statements:
         - conditions:
             match-neighbor-set:
                 neighbor-set: int
           actions:
               bgp-actions:
                  set-next-hop: 192.168.59.111
   - name: drop-vip
     statements:
         - conditions:
             match-prefix-set:
                 prefix-set: vip
             match-neighbor-set:
                 neighbor-set: ext
           actions:
               route-disposition: reject-route
   - name: set-next-hop-vip
     statements:
         - conditions:
             match-prefix-set:
                 prefix-set: vip
                 match-set-options: invert
             match-neighbor-set:
                 neighbor-set: ext
           actions:
               bgp-actions:
                  set-next-hop: 192.168.58.150
