apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan1
spec:
  config: '{
            "cniVersion": "1.0.0",
            "type": "macvlan",
            "master": "eth2",
            "mode": "bridge",
            "ipam": {
                "type": "host-local",
                "ranges": [
                    [ {
                         "subnet": "4.0.6.0/24",
                         "rangeStart": "4.0.6.3",
                         "rangeEnd": "4.0.6.100",
                         "gateway": "4.0.6.149"
                    } ]
                ],
                "routes": [
                    { "dst": "4.0.5.0/24", "gw": "4.0.6.149" },
                    { "dst": "4.0.4.0/24", "gw": "4.0.6.149" },
                    { "dst": "4.0.3.0/24", "gw": "4.0.6.149" }
                ]
            }
        }'
