apiVersion: v1
kind: Service
metadata:
  name: sctp-lb-fullnat
  annotations:
   loxilb.io/poolSelectSecondary: "pool2,pool3"
   loxilb.io/liveness: "yes"
   loxilb.io/lbmode: "fullnat"
spec:
  loadBalancerClass: loxilb.io/loxilb
  externalTrafficPolicy: Local
  selector:
    what: sctp-fullnat-test
  ports:
    - port: 57004
      protocol: SCTP
      targetPort: 9999
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: sctp-fullnat-test
  labels:
    what: sctp-fullnat-test
spec:
  containers:
    - name: sctp-fullnat-test
      image: loxilbio/sctp-darn:latest
      imagePullPolicy: Always
      #command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 6 ; done"]
      command: ["sctp_darn","-H", "0.0.0.0","-P", "9999", "-l"]
      ports:
        - containerPort: 9999
      env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
