# -*- mode: ruby -*-
# vi: set ft=ruby :

workers = (ENV['WORKERS'] || "1").to_i
#box_name = (ENV['VAGRANT_BOX'] || "ubuntu/focal64")
box_name = (ENV['VAGRANT_BOX'] || "sysnet4admin/Ubuntu-k8s")
box_version = "0.7.1"
Vagrant.configure("2") do |config|
  config.vm.box = "#{box_name}"
  config.vm.box_version = "#{box_version}"

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.define "bastion" do |bastion|
    bastion.vm.hostname = 'bastion'
    bastion.vm.network :private_network, ip: "4.0.5.3", :netmask => "255.255.255.0"
    bastion.vm.provision :shell, :path => "bastion.sh"
    bastion.vm.provider :virtualbox do |vbox|
        vbox.customize ["modifyvm", :id, "--memory", 2048]
        vbox.customize ["modifyvm", :id, "--cpus", 2]
        vbox.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
    end
  end

  config.vm.define "loxilb" do |loxilb|
    loxilb.vm.hostname = 'llb1'
    loxilb.vm.network :private_network, ip: "4.0.5.2", :netmask => "255.255.255.0"
    loxilb.vm.network :private_network, ip: "4.0.6.149", :netmask => "255.255.255.0"
    loxilb.vm.provision :shell, :path => "loxilb.sh"
    loxilb.vm.provider :virtualbox do |vbox|
        vbox.customize ["modifyvm", :id, "--memory", 6000]
        vbox.customize ["modifyvm", :id, "--cpus", 4]
        vbox.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
        vbox.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
    end
  end

  config.vm.define "master" do |master|
    master.vm.hostname = 'master'
    master.vm.network :private_network, ip: "192.168.80.10", :netmask => "255.255.255.0"
    master.vm.network :private_network, ip: "4.0.6.150", :netmask => "255.255.255.0"
    master.vm.provision :shell, :path => "master.sh"
    master.vm.provider :virtualbox do |vbox|
        vbox.customize ["modifyvm", :id, "--memory", 4096]
        vbox.customize ["modifyvm", :id, "--cpus", 4]
        vbox.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
        vbox.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
    end
  end
end
