# -*- mode: ruby -*-
# vi: set ft=ruby :

servers = (ENV['SERVERS'] || "1").to_i
#box_name = (ENV['VAGRANT_BOX'] || "ubuntu/focal64")
box_name = (ENV['VAGRANT_BOX'] || "sysnet4admin/Ubuntu-k8s")
box_version = "0.7.1"
Vagrant.configure("2") do |config|
  config.vm.box = "#{box_name}"
  config.vm.box_version = "#{box_version}"

  config.vm.define "loxilb" do |loxilb|
    loxilb.vm.hostname = 'llb1'
    #loxilb.vm.network "forwarded_port", guest: 55002, host: 5502, protocol: "tcp"
    loxilb.vm.network :private_network, ip: "192.168.80.9", :netmask => "255.255.255.0"
    loxilb.vm.network :private_network, ip: "192.168.90.9", :netmask => "255.255.255.0"
    loxilb.vm.provision :shell, :path => "loxilb.sh"
    loxilb.vm.provider :virtualbox do |vbox|
        vbox.customize ["modifyvm", :id, "--memory", 6000]
        vbox.customize ["modifyvm", :id, "--cpus", 4]
    end
  end


  config.vm.define "client" do |client|
    client.vm.hostname = 'client'
    client.vm.network :private_network, ip: "192.168.80.10", :netmask => "255.255.255.0"
    client.vm.provision :shell, :path => "client.sh"
    client.vm.provider :virtualbox do |vbox|
        vbox.customize ["modifyvm", :id, "--memory", 4096]
        vbox.customize ["modifyvm", :id, "--cpus", 2]
    end
  end

  (1..servers).each do |node_number|
    config.vm.define "server#{node_number}" do |server|
      server.vm.hostname = "server#{node_number}"
      ip = node_number + 100
      server.vm.network :private_network, ip: "192.168.80.#{ip}", :netmask => "255.255.255.0"
      server.vm.provision :shell, :path => "server.sh"
      server.vm.provider :virtualbox do |vbox|
          vbox.customize ["modifyvm", :id, "--memory", 4096]
          vbox.customize ["modifyvm", :id, "--cpus", 2]
      end
    end
  end
end
