// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: loxinet/xsync.proto

package loxinet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type XSyncReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response int32 `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *XSyncReply) Reset() {
	*x = XSyncReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_loxinet_xsync_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSyncReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSyncReply) ProtoMessage() {}

func (x *XSyncReply) ProtoReflect() protoreflect.Message {
	mi := &file_loxinet_xsync_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSyncReply.ProtoReflect.Descriptor instead.
func (*XSyncReply) Descriptor() ([]byte, []int) {
	return file_loxinet_xsync_proto_rawDescGZIP(), []int{0}
}

func (x *XSyncReply) GetResponse() int32 {
	if x != nil {
		return x.Response
	}
	return 0
}

type ConnGet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Async int32 `protobuf:"varint,1,opt,name=async,proto3" json:"async,omitempty"`
}

func (x *ConnGet) Reset() {
	*x = ConnGet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_loxinet_xsync_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnGet) ProtoMessage() {}

func (x *ConnGet) ProtoReflect() protoreflect.Message {
	mi := &file_loxinet_xsync_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnGet.ProtoReflect.Descriptor instead.
func (*ConnGet) Descriptor() ([]byte, []int) {
	return file_loxinet_xsync_proto_rawDescGZIP(), []int{1}
}

func (x *ConnGet) GetAsync() int32 {
	if x != nil {
		return x.Async
	}
	return 0
}

type CtInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dip        []byte `protobuf:"bytes,1,opt,name=dip,proto3" json:"dip,omitempty"`
	Sip        []byte `protobuf:"bytes,2,opt,name=sip,proto3" json:"sip,omitempty"`
	Dport      int32  `protobuf:"varint,3,opt,name=dport,proto3" json:"dport,omitempty"`
	Sport      int32  `protobuf:"varint,4,opt,name=sport,proto3" json:"sport,omitempty"`
	Proto      string `protobuf:"bytes,5,opt,name=proto,proto3" json:"proto,omitempty"`
	Cstate     string `protobuf:"bytes,6,opt,name=cstate,proto3" json:"cstate,omitempty"`
	Cact       string `protobuf:"bytes,7,opt,name=cact,proto3" json:"cact,omitempty"`
	Ci         string `protobuf:"bytes,8,opt,name=ci,proto3" json:"ci,omitempty"`
	Packets    int64  `protobuf:"varint,9,opt,name=packets,proto3" json:"packets,omitempty"`
	Bytes      int64  `protobuf:"varint,10,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Deleted    int32  `protobuf:"varint,11,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Pkey       []byte `protobuf:"bytes,12,opt,name=pkey,proto3" json:"pkey,omitempty"`
	Pval       []byte `protobuf:"bytes,13,opt,name=pval,proto3" json:"pval,omitempty"`
	Xsync      bool   `protobuf:"varint,14,opt,name=xsync,proto3" json:"xsync,omitempty"`
	Serviceip  []byte `protobuf:"bytes,15,opt,name=serviceip,proto3" json:"serviceip,omitempty"`
	Servproto  string `protobuf:"bytes,16,opt,name=servproto,proto3" json:"servproto,omitempty"`
	L4Servport int32  `protobuf:"varint,17,opt,name=l4servport,proto3" json:"l4servport,omitempty"`
	Blocknum   int32  `protobuf:"varint,18,opt,name=blocknum,proto3" json:"blocknum,omitempty"`
}

func (x *CtInfo) Reset() {
	*x = CtInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_loxinet_xsync_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CtInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtInfo) ProtoMessage() {}

func (x *CtInfo) ProtoReflect() protoreflect.Message {
	mi := &file_loxinet_xsync_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtInfo.ProtoReflect.Descriptor instead.
func (*CtInfo) Descriptor() ([]byte, []int) {
	return file_loxinet_xsync_proto_rawDescGZIP(), []int{2}
}

func (x *CtInfo) GetDip() []byte {
	if x != nil {
		return x.Dip
	}
	return nil
}

func (x *CtInfo) GetSip() []byte {
	if x != nil {
		return x.Sip
	}
	return nil
}

func (x *CtInfo) GetDport() int32 {
	if x != nil {
		return x.Dport
	}
	return 0
}

func (x *CtInfo) GetSport() int32 {
	if x != nil {
		return x.Sport
	}
	return 0
}

func (x *CtInfo) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *CtInfo) GetCstate() string {
	if x != nil {
		return x.Cstate
	}
	return ""
}

func (x *CtInfo) GetCact() string {
	if x != nil {
		return x.Cact
	}
	return ""
}

func (x *CtInfo) GetCi() string {
	if x != nil {
		return x.Ci
	}
	return ""
}

func (x *CtInfo) GetPackets() int64 {
	if x != nil {
		return x.Packets
	}
	return 0
}

func (x *CtInfo) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *CtInfo) GetDeleted() int32 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

func (x *CtInfo) GetPkey() []byte {
	if x != nil {
		return x.Pkey
	}
	return nil
}

func (x *CtInfo) GetPval() []byte {
	if x != nil {
		return x.Pval
	}
	return nil
}

func (x *CtInfo) GetXsync() bool {
	if x != nil {
		return x.Xsync
	}
	return false
}

func (x *CtInfo) GetServiceip() []byte {
	if x != nil {
		return x.Serviceip
	}
	return nil
}

func (x *CtInfo) GetServproto() string {
	if x != nil {
		return x.Servproto
	}
	return ""
}

func (x *CtInfo) GetL4Servport() int32 {
	if x != nil {
		return x.L4Servport
	}
	return 0
}

func (x *CtInfo) GetBlocknum() int32 {
	if x != nil {
		return x.Blocknum
	}
	return 0
}

type CtInfoMod struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Add bool    `protobuf:"varint,1,opt,name=add,proto3" json:"add,omitempty"`
	Ct  *CtInfo `protobuf:"bytes,2,opt,name=ct,proto3" json:"ct,omitempty"`
}

func (x *CtInfoMod) Reset() {
	*x = CtInfoMod{}
	if protoimpl.UnsafeEnabled {
		mi := &file_loxinet_xsync_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CtInfoMod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtInfoMod) ProtoMessage() {}

func (x *CtInfoMod) ProtoReflect() protoreflect.Message {
	mi := &file_loxinet_xsync_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtInfoMod.ProtoReflect.Descriptor instead.
func (*CtInfoMod) Descriptor() ([]byte, []int) {
	return file_loxinet_xsync_proto_rawDescGZIP(), []int{3}
}

func (x *CtInfoMod) GetAdd() bool {
	if x != nil {
		return x.Add
	}
	return false
}

func (x *CtInfoMod) GetCt() *CtInfo {
	if x != nil {
		return x.Ct
	}
	return nil
}

type BlockCtInfoMod struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Add bool      `protobuf:"varint,1,opt,name=add,proto3" json:"add,omitempty"`
	Ct  []*CtInfo `protobuf:"bytes,2,rep,name=ct,proto3" json:"ct,omitempty"`
}

func (x *BlockCtInfoMod) Reset() {
	*x = BlockCtInfoMod{}
	if protoimpl.UnsafeEnabled {
		mi := &file_loxinet_xsync_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockCtInfoMod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockCtInfoMod) ProtoMessage() {}

func (x *BlockCtInfoMod) ProtoReflect() protoreflect.Message {
	mi := &file_loxinet_xsync_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockCtInfoMod.ProtoReflect.Descriptor instead.
func (*BlockCtInfoMod) Descriptor() ([]byte, []int) {
	return file_loxinet_xsync_proto_rawDescGZIP(), []int{4}
}

func (x *BlockCtInfoMod) GetAdd() bool {
	if x != nil {
		return x.Add
	}
	return false
}

func (x *BlockCtInfoMod) GetCt() []*CtInfo {
	if x != nil {
		return x.Ct
	}
	return nil
}

var File_loxinet_xsync_proto protoreflect.FileDescriptor

var file_loxinet_xsync_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6c, 0x6f, 0x78, 0x69, 0x6e, 0x65, 0x74, 0x2f, 0x78, 0x73, 0x79, 0x6e, 0x63, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x28, 0x0a, 0x0a, 0x58, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x1f, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x47, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x73,
	0x79, 0x6e, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x61, 0x73, 0x79, 0x6e, 0x63,
	0x22, 0xaa, 0x03, 0x0a, 0x06, 0x43, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x64,
	0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x64, 0x69, 0x70, 0x12, 0x10, 0x0a,
	0x03, 0x73, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x73, 0x69, 0x70, 0x12,
	0x14, 0x0a, 0x05, 0x64, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x64, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x63, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x61, 0x63,
	0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x61, 0x63, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x63, 0x69, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x63, 0x69, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6b, 0x65, 0x79, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x70, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x76, 0x61, 0x6c, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x70, 0x76, 0x61, 0x6c, 0x12,
	0x14, 0x0a, 0x05, 0x78, 0x73, 0x79, 0x6e, 0x63, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x78, 0x73, 0x79, 0x6e, 0x63, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x69, 0x70, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x69, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x34, 0x73, 0x65, 0x72, 0x76, 0x70, 0x6f, 0x72, 0x74, 0x18,
	0x11, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6c, 0x34, 0x73, 0x65, 0x72, 0x76, 0x70, 0x6f, 0x72,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x6e, 0x75, 0x6d, 0x18, 0x12, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x6e, 0x75, 0x6d, 0x22, 0x36, 0x0a,
	0x09, 0x43, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x6f, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x64,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x61, 0x64, 0x64, 0x12, 0x17, 0x0a, 0x02,
	0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x43, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x02, 0x63, 0x74, 0x22, 0x3b, 0x0a, 0x0e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x43, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x6f, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x64, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x61, 0x64, 0x64, 0x12, 0x17, 0x0a, 0x02, 0x63, 0x74, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x43, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x02,
	0x63, 0x74, 0x32, 0x9f, 0x01, 0x0a, 0x05, 0x58, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x2c, 0x0a, 0x11,
	0x44, 0x70, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x6e, 0x43, 0x74, 0x47, 0x65, 0x74, 0x47, 0x52, 0x50,
	0x43, 0x12, 0x08, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x47, 0x65, 0x74, 0x1a, 0x0b, 0x2e, 0x58, 0x53,
	0x79, 0x6e, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x11, 0x44, 0x70,
	0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x6e, 0x43, 0x74, 0x4d, 0x6f, 0x64, 0x47, 0x52, 0x50, 0x43, 0x12,
	0x0a, 0x2e, 0x43, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x6f, 0x64, 0x1a, 0x0b, 0x2e, 0x58, 0x53,
	0x79, 0x6e, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x16, 0x44, 0x70,
	0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x43, 0x74, 0x4d, 0x6f, 0x64,
	0x47, 0x52, 0x50, 0x43, 0x12, 0x0f, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x43, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x4d, 0x6f, 0x64, 0x1a, 0x0b, 0x2e, 0x58, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x6c, 0x6f, 0x78, 0x69, 0x6e, 0x65,
	0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_loxinet_xsync_proto_rawDescOnce sync.Once
	file_loxinet_xsync_proto_rawDescData = file_loxinet_xsync_proto_rawDesc
)

func file_loxinet_xsync_proto_rawDescGZIP() []byte {
	file_loxinet_xsync_proto_rawDescOnce.Do(func() {
		file_loxinet_xsync_proto_rawDescData = protoimpl.X.CompressGZIP(file_loxinet_xsync_proto_rawDescData)
	})
	return file_loxinet_xsync_proto_rawDescData
}

var file_loxinet_xsync_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_loxinet_xsync_proto_goTypes = []interface{}{
	(*XSyncReply)(nil),     // 0: XSyncReply
	(*ConnGet)(nil),        // 1: ConnGet
	(*CtInfo)(nil),         // 2: CtInfo
	(*CtInfoMod)(nil),      // 3: CtInfoMod
	(*BlockCtInfoMod)(nil), // 4: BlockCtInfoMod
}
var file_loxinet_xsync_proto_depIdxs = []int32{
	2, // 0: CtInfoMod.ct:type_name -> CtInfo
	2, // 1: BlockCtInfoMod.ct:type_name -> CtInfo
	1, // 2: XSync.DpWorkOnCtGetGRPC:input_type -> ConnGet
	3, // 3: XSync.DpWorkOnCtModGRPC:input_type -> CtInfoMod
	4, // 4: XSync.DpWorkOnBlockCtModGRPC:input_type -> BlockCtInfoMod
	0, // 5: XSync.DpWorkOnCtGetGRPC:output_type -> XSyncReply
	0, // 6: XSync.DpWorkOnCtModGRPC:output_type -> XSyncReply
	0, // 7: XSync.DpWorkOnBlockCtModGRPC:output_type -> XSyncReply
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_loxinet_xsync_proto_init() }
func file_loxinet_xsync_proto_init() {
	if File_loxinet_xsync_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_loxinet_xsync_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSyncReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_loxinet_xsync_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnGet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_loxinet_xsync_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CtInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_loxinet_xsync_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CtInfoMod); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_loxinet_xsync_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockCtInfoMod); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_loxinet_xsync_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_loxinet_xsync_proto_goTypes,
		DependencyIndexes: file_loxinet_xsync_proto_depIdxs,
		MessageInfos:      file_loxinet_xsync_proto_msgTypes,
	}.Build()
	File_loxinet_xsync_proto = out.File
	file_loxinet_xsync_proto_rawDesc = nil
	file_loxinet_xsync_proto_goTypes = nil
	file_loxinet_xsync_proto_depIdxs = nil
}
