apiVersion: v1
kind: Service
metadata:
  name: iperf-service
  annotations:
    loxilb.io/lbmode: "onearm" 
    loxilb.io/prefLocalPod: "yes"
spec:
  externalTrafficPolicy: Local
  loadBalancerClass: loxilb.io/loxilb
  selector:
    app: iperf-app
  ports:
    - port: 55001
      targetPort: 5001
  type: LoadBalancer
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iperf-daemonset
  labels:
    app: iperf-app
spec:
  selector:
    matchLabels:
      app: iperf-app
  template:
    metadata:
      labels:
        app: iperf-app
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "node-role.kubernetes.io/master"
                operator: DoesNotExist
              - key: "node-role.kubernetes.io/control-plane"
                operator: DoesNotExist
      containers:
      - name: iperf
        image: eyes852/ubuntu-iperf-test:0.5
        command: [ "iperf", "-s"]
        ports:
        - containerPort: 5001
