apiVersion: v1
kind: Service
metadata:
  name: sctp-lb-fullnat
  annotations:
    #loxilb.io/num-secondary-networks: "2"
   loxilb.io/liveness: "yes"
   loxilb.io/lbmode: "fullnat"
spec:
  loadBalancerClass: loxilb.io/loxilb
  externalTrafficPolicy: Local
  selector:
    what: sctp-fullnat-test
  ports:
    - port: 57004
      protocol: SCTP
      targetPort: 9999
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: sctp-fullnat-test
  labels:
    what: sctp-fullnat-test
spec:
  containers:
    - name: sctp-fullnat-test
      #image: loxilbio/sctp-darn:latest
      image: ghcr.io/loxilb-io/alpine-socat:latest
      imagePullPolicy: Always
      #command: ["sctp_darn","-H", "0.0.0.0","-P", "9999", "-l"]
      command: [ "sh", "-c"]
      args:
      - while true; do
          socat -v -T2 sctp-l:9999,reuseaddr,fork system:"echo 'server1'; cat";
          sleep 20;
        done;
      ports:
        - containerPort: 9999
      env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
