apiVersion: v1
kind: Service
metadata:
  name: sctp-lb-fullnat
  annotations:
    loxilb.io/lbmode: "fullnat"
    loxilb.io/liveness: "yes"
    loxilb.io/probetype: "ping"
spec:
  externalTrafficPolicy: Local
  loadBalancerClass: loxilb.io/loxilb
  selector:
    what: sctp-fullnat-test
  ports:
    - port: 56004
      protocol: SCTP
      targetPort: 9999
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: sctp-fullnat-test
  labels:
    what: sctp-fullnat-test
spec:
  containers:
    - name: sctp-fullnat-test
      image: loxilbio/sctp-darn:latest
      imagePullPolicy: Always
      #command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 6 ; done"]
      command: ["sctp_darn","-H", "0.0.0.0","-P", "9999", "-l"]
      #command: ["sctp_test","-H", "0.0.0.0","-P", "9999", "-l"]
      ports:
        - containerPort: 9999
