apiVersion: v1
kind: Service
metadata:
  name: tcp-lb-default
  annotations:
    loxilb.io/lbmode: "default"
      #loxilb.io/liveness: "yes"
      #loxilb.io/probetype: "ping"
spec:
  externalTrafficPolicy: Local
  loadBalancerClass: loxilb.io/loxilb
  selector:
    what: tcp-default-test
  ports:
    - port: 56003
      targetPort: 5001
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: tcp-default-test
  labels:
    what: tcp-default-test
spec:
  containers:
    - name: tcp-default-test
      image: eyes852/ubuntu-iperf-test:0.5
      command:
        - iperf
        - "-s"
      ports:
        - containerPort: 5001
