// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// DeleteConfigEndpointEpipaddressIPAddressNoContentCode is the HTTP code returned for type DeleteConfigEndpointEpipaddressIPAddressNoContent
const DeleteConfigEndpointEpipaddressIPAddressNoContentCode int = 204

/*
DeleteConfigEndpointEpipaddressIPAddressNoContent OK

swagger:response deleteConfigEndpointEpipaddressIpAddressNoContent
*/
type DeleteConfigEndpointEpipaddressIPAddressNoContent struct {
}

// NewDeleteConfigEndpointEpipaddressIPAddressNoContent creates DeleteConfigEndpointEpipaddressIPAddressNoContent with default headers values
func NewDeleteConfigEndpointEpipaddressIPAddressNoContent() *DeleteConfigEndpointEpipaddressIPAddressNoContent {

	return &DeleteConfigEndpointEpipaddressIPAddressNoContent{}
}

// WriteResponse to the client
func (o *DeleteConfigEndpointEpipaddressIPAddressNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteConfigEndpointEpipaddressIPAddressBadRequestCode is the HTTP code returned for type DeleteConfigEndpointEpipaddressIPAddressBadRequest
const DeleteConfigEndpointEpipaddressIPAddressBadRequestCode int = 400

/*
DeleteConfigEndpointEpipaddressIPAddressBadRequest Malformed arguments for API call

swagger:response deleteConfigEndpointEpipaddressIpAddressBadRequest
*/
type DeleteConfigEndpointEpipaddressIPAddressBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigEndpointEpipaddressIPAddressBadRequest creates DeleteConfigEndpointEpipaddressIPAddressBadRequest with default headers values
func NewDeleteConfigEndpointEpipaddressIPAddressBadRequest() *DeleteConfigEndpointEpipaddressIPAddressBadRequest {

	return &DeleteConfigEndpointEpipaddressIPAddressBadRequest{}
}

// WithPayload adds the payload to the delete config endpoint epipaddress Ip address bad request response
func (o *DeleteConfigEndpointEpipaddressIPAddressBadRequest) WithPayload(payload *models.Error) *DeleteConfigEndpointEpipaddressIPAddressBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config endpoint epipaddress Ip address bad request response
func (o *DeleteConfigEndpointEpipaddressIPAddressBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigEndpointEpipaddressIPAddressBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigEndpointEpipaddressIPAddressUnauthorizedCode is the HTTP code returned for type DeleteConfigEndpointEpipaddressIPAddressUnauthorized
const DeleteConfigEndpointEpipaddressIPAddressUnauthorizedCode int = 401

/*
DeleteConfigEndpointEpipaddressIPAddressUnauthorized Invalid authentication credentials

swagger:response deleteConfigEndpointEpipaddressIpAddressUnauthorized
*/
type DeleteConfigEndpointEpipaddressIPAddressUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigEndpointEpipaddressIPAddressUnauthorized creates DeleteConfigEndpointEpipaddressIPAddressUnauthorized with default headers values
func NewDeleteConfigEndpointEpipaddressIPAddressUnauthorized() *DeleteConfigEndpointEpipaddressIPAddressUnauthorized {

	return &DeleteConfigEndpointEpipaddressIPAddressUnauthorized{}
}

// WithPayload adds the payload to the delete config endpoint epipaddress Ip address unauthorized response
func (o *DeleteConfigEndpointEpipaddressIPAddressUnauthorized) WithPayload(payload *models.Error) *DeleteConfigEndpointEpipaddressIPAddressUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config endpoint epipaddress Ip address unauthorized response
func (o *DeleteConfigEndpointEpipaddressIPAddressUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigEndpointEpipaddressIPAddressUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigEndpointEpipaddressIPAddressForbiddenCode is the HTTP code returned for type DeleteConfigEndpointEpipaddressIPAddressForbidden
const DeleteConfigEndpointEpipaddressIPAddressForbiddenCode int = 403

/*
DeleteConfigEndpointEpipaddressIPAddressForbidden Capacity insufficient

swagger:response deleteConfigEndpointEpipaddressIpAddressForbidden
*/
type DeleteConfigEndpointEpipaddressIPAddressForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigEndpointEpipaddressIPAddressForbidden creates DeleteConfigEndpointEpipaddressIPAddressForbidden with default headers values
func NewDeleteConfigEndpointEpipaddressIPAddressForbidden() *DeleteConfigEndpointEpipaddressIPAddressForbidden {

	return &DeleteConfigEndpointEpipaddressIPAddressForbidden{}
}

// WithPayload adds the payload to the delete config endpoint epipaddress Ip address forbidden response
func (o *DeleteConfigEndpointEpipaddressIPAddressForbidden) WithPayload(payload *models.Error) *DeleteConfigEndpointEpipaddressIPAddressForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config endpoint epipaddress Ip address forbidden response
func (o *DeleteConfigEndpointEpipaddressIPAddressForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigEndpointEpipaddressIPAddressForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigEndpointEpipaddressIPAddressNotFoundCode is the HTTP code returned for type DeleteConfigEndpointEpipaddressIPAddressNotFound
const DeleteConfigEndpointEpipaddressIPAddressNotFoundCode int = 404

/*
DeleteConfigEndpointEpipaddressIPAddressNotFound Resource not found

swagger:response deleteConfigEndpointEpipaddressIpAddressNotFound
*/
type DeleteConfigEndpointEpipaddressIPAddressNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigEndpointEpipaddressIPAddressNotFound creates DeleteConfigEndpointEpipaddressIPAddressNotFound with default headers values
func NewDeleteConfigEndpointEpipaddressIPAddressNotFound() *DeleteConfigEndpointEpipaddressIPAddressNotFound {

	return &DeleteConfigEndpointEpipaddressIPAddressNotFound{}
}

// WithPayload adds the payload to the delete config endpoint epipaddress Ip address not found response
func (o *DeleteConfigEndpointEpipaddressIPAddressNotFound) WithPayload(payload *models.Error) *DeleteConfigEndpointEpipaddressIPAddressNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config endpoint epipaddress Ip address not found response
func (o *DeleteConfigEndpointEpipaddressIPAddressNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigEndpointEpipaddressIPAddressNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigEndpointEpipaddressIPAddressConflictCode is the HTTP code returned for type DeleteConfigEndpointEpipaddressIPAddressConflict
const DeleteConfigEndpointEpipaddressIPAddressConflictCode int = 409

/*
DeleteConfigEndpointEpipaddressIPAddressConflict Resource Conflict. VLAN already exists OR dependency VRF/VNET not found

swagger:response deleteConfigEndpointEpipaddressIpAddressConflict
*/
type DeleteConfigEndpointEpipaddressIPAddressConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigEndpointEpipaddressIPAddressConflict creates DeleteConfigEndpointEpipaddressIPAddressConflict with default headers values
func NewDeleteConfigEndpointEpipaddressIPAddressConflict() *DeleteConfigEndpointEpipaddressIPAddressConflict {

	return &DeleteConfigEndpointEpipaddressIPAddressConflict{}
}

// WithPayload adds the payload to the delete config endpoint epipaddress Ip address conflict response
func (o *DeleteConfigEndpointEpipaddressIPAddressConflict) WithPayload(payload *models.Error) *DeleteConfigEndpointEpipaddressIPAddressConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config endpoint epipaddress Ip address conflict response
func (o *DeleteConfigEndpointEpipaddressIPAddressConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigEndpointEpipaddressIPAddressConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigEndpointEpipaddressIPAddressInternalServerErrorCode is the HTTP code returned for type DeleteConfigEndpointEpipaddressIPAddressInternalServerError
const DeleteConfigEndpointEpipaddressIPAddressInternalServerErrorCode int = 500

/*
DeleteConfigEndpointEpipaddressIPAddressInternalServerError Internal service error

swagger:response deleteConfigEndpointEpipaddressIpAddressInternalServerError
*/
type DeleteConfigEndpointEpipaddressIPAddressInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigEndpointEpipaddressIPAddressInternalServerError creates DeleteConfigEndpointEpipaddressIPAddressInternalServerError with default headers values
func NewDeleteConfigEndpointEpipaddressIPAddressInternalServerError() *DeleteConfigEndpointEpipaddressIPAddressInternalServerError {

	return &DeleteConfigEndpointEpipaddressIPAddressInternalServerError{}
}

// WithPayload adds the payload to the delete config endpoint epipaddress Ip address internal server error response
func (o *DeleteConfigEndpointEpipaddressIPAddressInternalServerError) WithPayload(payload *models.Error) *DeleteConfigEndpointEpipaddressIPAddressInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config endpoint epipaddress Ip address internal server error response
func (o *DeleteConfigEndpointEpipaddressIPAddressInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigEndpointEpipaddressIPAddressInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigEndpointEpipaddressIPAddressServiceUnavailableCode is the HTTP code returned for type DeleteConfigEndpointEpipaddressIPAddressServiceUnavailable
const DeleteConfigEndpointEpipaddressIPAddressServiceUnavailableCode int = 503

/*
DeleteConfigEndpointEpipaddressIPAddressServiceUnavailable Maintanence mode

swagger:response deleteConfigEndpointEpipaddressIpAddressServiceUnavailable
*/
type DeleteConfigEndpointEpipaddressIPAddressServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigEndpointEpipaddressIPAddressServiceUnavailable creates DeleteConfigEndpointEpipaddressIPAddressServiceUnavailable with default headers values
func NewDeleteConfigEndpointEpipaddressIPAddressServiceUnavailable() *DeleteConfigEndpointEpipaddressIPAddressServiceUnavailable {

	return &DeleteConfigEndpointEpipaddressIPAddressServiceUnavailable{}
}

// WithPayload adds the payload to the delete config endpoint epipaddress Ip address service unavailable response
func (o *DeleteConfigEndpointEpipaddressIPAddressServiceUnavailable) WithPayload(payload *models.Error) *DeleteConfigEndpointEpipaddressIPAddressServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config endpoint epipaddress Ip address service unavailable response
func (o *DeleteConfigEndpointEpipaddressIPAddressServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigEndpointEpipaddressIPAddressServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
