// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteConfigMirrorIdentIdentHandlerFunc turns a function with the right signature into a delete config mirror ident ident handler
type DeleteConfigMirrorIdentIdentHandlerFunc func(DeleteConfigMirrorIdentIdentParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteConfigMirrorIdentIdentHandlerFunc) Handle(params DeleteConfigMirrorIdentIdentParams) middleware.Responder {
	return fn(params)
}

// DeleteConfigMirrorIdentIdentHandler interface for that can handle valid delete config mirror ident ident params
type DeleteConfigMirrorIdentIdentHandler interface {
	Handle(DeleteConfigMirrorIdentIdentParams) middleware.Responder
}

// NewDeleteConfigMirrorIdentIdent creates a new http.Handler for the delete config mirror ident ident operation
func NewDeleteConfigMirrorIdentIdent(ctx *middleware.Context, handler DeleteConfigMirrorIdentIdentHandler) *DeleteConfigMirrorIdentIdent {
	return &DeleteConfigMirrorIdentIdent{Context: ctx, Handler: handler}
}

/*
	DeleteConfigMirrorIdentIdent swagger:route DELETE /config/mirror/ident/{ident} deleteConfigMirrorIdentIdent

# Delete a Mirror service

Delete a new Create a Mirror service.
*/
type DeleteConfigMirrorIdentIdent struct {
	Context *middleware.Context
	Handler DeleteConfigMirrorIdentIdentHandler
}

func (o *DeleteConfigMirrorIdentIdent) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteConfigMirrorIdentIdentParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
