// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteConfigBfdRemoteIPRemoteIPHandlerFunc turns a function with the right signature into a delete config bfd remote IP remote IP handler
type DeleteConfigBfdRemoteIPRemoteIPHandlerFunc func(DeleteConfigBfdRemoteIPRemoteIPParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteConfigBfdRemoteIPRemoteIPHandlerFunc) Handle(params DeleteConfigBfdRemoteIPRemoteIPParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteConfigBfdRemoteIPRemoteIPHandler interface for that can handle valid delete config bfd remote IP remote IP params
type DeleteConfigBfdRemoteIPRemoteIPHandler interface {
	Handle(DeleteConfigBfdRemoteIPRemoteIPParams, interface{}) middleware.Responder
}

// NewDeleteConfigBfdRemoteIPRemoteIP creates a new http.Handler for the delete config bfd remote IP remote IP operation
func NewDeleteConfigBfdRemoteIPRemoteIP(ctx *middleware.Context, handler DeleteConfigBfdRemoteIPRemoteIPHandler) *DeleteConfigBfdRemoteIPRemoteIP {
	return &DeleteConfigBfdRemoteIPRemoteIP{Context: ctx, Handler: handler}
}

/*
	DeleteConfigBfdRemoteIPRemoteIP swagger:route DELETE /config/bfd/remoteIP/{remote_ip} deleteConfigBfdRemoteIpRemoteIp

# Delete a BFD session

Delete a BFD session
*/
type DeleteConfigBfdRemoteIPRemoteIP struct {
	Context *middleware.Context
	Handler DeleteConfigBfdRemoteIPRemoteIPHandler
}

func (o *DeleteConfigBfdRemoteIPRemoteIP) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteConfigBfdRemoteIPRemoteIPParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
