// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteConfigBfdRemoteIPHandlerFunc turns a function with the right signature into a delete config bfd remote IP handler
type DeleteConfigBfdRemoteIPHandlerFunc func(DeleteConfigBfdRemoteIPParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteConfigBfdRemoteIPHandlerFunc) Handle(params DeleteConfigBfdRemoteIPParams) middleware.Responder {
	return fn(params)
}

// DeleteConfigBfdRemoteIPHandler interface for that can handle valid delete config bfd remote IP params
type DeleteConfigBfdRemoteIPHandler interface {
	Handle(DeleteConfigBfdRemoteIPParams) middleware.Responder
}

// NewDeleteConfigBfdRemoteIP creates a new http.Handler for the delete config bfd remote IP operation
func NewDeleteConfigBfdRemoteIP(ctx *middleware.Context, handler DeleteConfigBfdRemoteIPHandler) *DeleteConfigBfdRemoteIP {
	return &DeleteConfigBfdRemoteIP{Context: ctx, Handler: handler}
}

/*
	DeleteConfigBfdRemoteIP swagger:route DELETE /config/bfd/{remote_ip} deleteConfigBfdRemoteIp

# Delete a BFD session

Delete a BFD session
*/
type DeleteConfigBfdRemoteIP struct {
	Context *middleware.Context
	Handler DeleteConfigBfdRemoteIPHandler
}

func (o *DeleteConfigBfdRemoteIP) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteConfigBfdRemoteIPParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
