// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"loxilb/api/models"
)

// DeleteConfigRouteDestinationIPIPAddressNoContentCode is the HTTP code returned for type DeleteConfigRouteDestinationIPIPAddressNoContent
const DeleteConfigRouteDestinationIPIPAddressNoContentCode int = 204

/*DeleteConfigRouteDestinationIPIPAddressNoContent OK

swagger:response deleteConfigRouteDestinationIpIpAddressNoContent
*/
type DeleteConfigRouteDestinationIPIPAddressNoContent struct {
}

// NewDeleteConfigRouteDestinationIPIPAddressNoContent creates DeleteConfigRouteDestinationIPIPAddressNoContent with default headers values
func NewDeleteConfigRouteDestinationIPIPAddressNoContent() *DeleteConfigRouteDestinationIPIPAddressNoContent {

	return &DeleteConfigRouteDestinationIPIPAddressNoContent{}
}

// WriteResponse to the client
func (o *DeleteConfigRouteDestinationIPIPAddressNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteConfigRouteDestinationIPIPAddressBadRequestCode is the HTTP code returned for type DeleteConfigRouteDestinationIPIPAddressBadRequest
const DeleteConfigRouteDestinationIPIPAddressBadRequestCode int = 400

/*DeleteConfigRouteDestinationIPIPAddressBadRequest Malformed arguments for API call

swagger:response deleteConfigRouteDestinationIpIpAddressBadRequest
*/
type DeleteConfigRouteDestinationIPIPAddressBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigRouteDestinationIPIPAddressBadRequest creates DeleteConfigRouteDestinationIPIPAddressBadRequest with default headers values
func NewDeleteConfigRouteDestinationIPIPAddressBadRequest() *DeleteConfigRouteDestinationIPIPAddressBadRequest {

	return &DeleteConfigRouteDestinationIPIPAddressBadRequest{}
}

// WithPayload adds the payload to the delete config route destination Ip Ip address bad request response
func (o *DeleteConfigRouteDestinationIPIPAddressBadRequest) WithPayload(payload *models.Error) *DeleteConfigRouteDestinationIPIPAddressBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config route destination Ip Ip address bad request response
func (o *DeleteConfigRouteDestinationIPIPAddressBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigRouteDestinationIPIPAddressBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigRouteDestinationIPIPAddressUnauthorizedCode is the HTTP code returned for type DeleteConfigRouteDestinationIPIPAddressUnauthorized
const DeleteConfigRouteDestinationIPIPAddressUnauthorizedCode int = 401

/*DeleteConfigRouteDestinationIPIPAddressUnauthorized Invalid authentication credentials

swagger:response deleteConfigRouteDestinationIpIpAddressUnauthorized
*/
type DeleteConfigRouteDestinationIPIPAddressUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigRouteDestinationIPIPAddressUnauthorized creates DeleteConfigRouteDestinationIPIPAddressUnauthorized with default headers values
func NewDeleteConfigRouteDestinationIPIPAddressUnauthorized() *DeleteConfigRouteDestinationIPIPAddressUnauthorized {

	return &DeleteConfigRouteDestinationIPIPAddressUnauthorized{}
}

// WithPayload adds the payload to the delete config route destination Ip Ip address unauthorized response
func (o *DeleteConfigRouteDestinationIPIPAddressUnauthorized) WithPayload(payload *models.Error) *DeleteConfigRouteDestinationIPIPAddressUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config route destination Ip Ip address unauthorized response
func (o *DeleteConfigRouteDestinationIPIPAddressUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigRouteDestinationIPIPAddressUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigRouteDestinationIPIPAddressForbiddenCode is the HTTP code returned for type DeleteConfigRouteDestinationIPIPAddressForbidden
const DeleteConfigRouteDestinationIPIPAddressForbiddenCode int = 403

/*DeleteConfigRouteDestinationIPIPAddressForbidden Capacity insufficient

swagger:response deleteConfigRouteDestinationIpIpAddressForbidden
*/
type DeleteConfigRouteDestinationIPIPAddressForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigRouteDestinationIPIPAddressForbidden creates DeleteConfigRouteDestinationIPIPAddressForbidden with default headers values
func NewDeleteConfigRouteDestinationIPIPAddressForbidden() *DeleteConfigRouteDestinationIPIPAddressForbidden {

	return &DeleteConfigRouteDestinationIPIPAddressForbidden{}
}

// WithPayload adds the payload to the delete config route destination Ip Ip address forbidden response
func (o *DeleteConfigRouteDestinationIPIPAddressForbidden) WithPayload(payload *models.Error) *DeleteConfigRouteDestinationIPIPAddressForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config route destination Ip Ip address forbidden response
func (o *DeleteConfigRouteDestinationIPIPAddressForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigRouteDestinationIPIPAddressForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigRouteDestinationIPIPAddressNotFoundCode is the HTTP code returned for type DeleteConfigRouteDestinationIPIPAddressNotFound
const DeleteConfigRouteDestinationIPIPAddressNotFoundCode int = 404

/*DeleteConfigRouteDestinationIPIPAddressNotFound Resource not found

swagger:response deleteConfigRouteDestinationIpIpAddressNotFound
*/
type DeleteConfigRouteDestinationIPIPAddressNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigRouteDestinationIPIPAddressNotFound creates DeleteConfigRouteDestinationIPIPAddressNotFound with default headers values
func NewDeleteConfigRouteDestinationIPIPAddressNotFound() *DeleteConfigRouteDestinationIPIPAddressNotFound {

	return &DeleteConfigRouteDestinationIPIPAddressNotFound{}
}

// WithPayload adds the payload to the delete config route destination Ip Ip address not found response
func (o *DeleteConfigRouteDestinationIPIPAddressNotFound) WithPayload(payload *models.Error) *DeleteConfigRouteDestinationIPIPAddressNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config route destination Ip Ip address not found response
func (o *DeleteConfigRouteDestinationIPIPAddressNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigRouteDestinationIPIPAddressNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigRouteDestinationIPIPAddressConflictCode is the HTTP code returned for type DeleteConfigRouteDestinationIPIPAddressConflict
const DeleteConfigRouteDestinationIPIPAddressConflictCode int = 409

/*DeleteConfigRouteDestinationIPIPAddressConflict Resource Conflict. VLAN already exists OR dependency VRF/VNET not found

swagger:response deleteConfigRouteDestinationIpIpAddressConflict
*/
type DeleteConfigRouteDestinationIPIPAddressConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigRouteDestinationIPIPAddressConflict creates DeleteConfigRouteDestinationIPIPAddressConflict with default headers values
func NewDeleteConfigRouteDestinationIPIPAddressConflict() *DeleteConfigRouteDestinationIPIPAddressConflict {

	return &DeleteConfigRouteDestinationIPIPAddressConflict{}
}

// WithPayload adds the payload to the delete config route destination Ip Ip address conflict response
func (o *DeleteConfigRouteDestinationIPIPAddressConflict) WithPayload(payload *models.Error) *DeleteConfigRouteDestinationIPIPAddressConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config route destination Ip Ip address conflict response
func (o *DeleteConfigRouteDestinationIPIPAddressConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigRouteDestinationIPIPAddressConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigRouteDestinationIPIPAddressInternalServerErrorCode is the HTTP code returned for type DeleteConfigRouteDestinationIPIPAddressInternalServerError
const DeleteConfigRouteDestinationIPIPAddressInternalServerErrorCode int = 500

/*DeleteConfigRouteDestinationIPIPAddressInternalServerError Internal service error

swagger:response deleteConfigRouteDestinationIpIpAddressInternalServerError
*/
type DeleteConfigRouteDestinationIPIPAddressInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigRouteDestinationIPIPAddressInternalServerError creates DeleteConfigRouteDestinationIPIPAddressInternalServerError with default headers values
func NewDeleteConfigRouteDestinationIPIPAddressInternalServerError() *DeleteConfigRouteDestinationIPIPAddressInternalServerError {

	return &DeleteConfigRouteDestinationIPIPAddressInternalServerError{}
}

// WithPayload adds the payload to the delete config route destination Ip Ip address internal server error response
func (o *DeleteConfigRouteDestinationIPIPAddressInternalServerError) WithPayload(payload *models.Error) *DeleteConfigRouteDestinationIPIPAddressInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config route destination Ip Ip address internal server error response
func (o *DeleteConfigRouteDestinationIPIPAddressInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigRouteDestinationIPIPAddressInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigRouteDestinationIPIPAddressServiceUnavailableCode is the HTTP code returned for type DeleteConfigRouteDestinationIPIPAddressServiceUnavailable
const DeleteConfigRouteDestinationIPIPAddressServiceUnavailableCode int = 503

/*DeleteConfigRouteDestinationIPIPAddressServiceUnavailable Maintanence mode

swagger:response deleteConfigRouteDestinationIpIpAddressServiceUnavailable
*/
type DeleteConfigRouteDestinationIPIPAddressServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigRouteDestinationIPIPAddressServiceUnavailable creates DeleteConfigRouteDestinationIPIPAddressServiceUnavailable with default headers values
func NewDeleteConfigRouteDestinationIPIPAddressServiceUnavailable() *DeleteConfigRouteDestinationIPIPAddressServiceUnavailable {

	return &DeleteConfigRouteDestinationIPIPAddressServiceUnavailable{}
}

// WithPayload adds the payload to the delete config route destination Ip Ip address service unavailable response
func (o *DeleteConfigRouteDestinationIPIPAddressServiceUnavailable) WithPayload(payload *models.Error) *DeleteConfigRouteDestinationIPIPAddressServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config route destination Ip Ip address service unavailable response
func (o *DeleteConfigRouteDestinationIPIPAddressServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigRouteDestinationIPIPAddressServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
