// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// DeleteConfigEndpointNoContentCode is the HTTP code returned for type DeleteConfigEndpointNoContent
const DeleteConfigEndpointNoContentCode int = 204

/*
DeleteConfigEndpointNoContent OK

swagger:response deleteConfigEndpointNoContent
*/
type DeleteConfigEndpointNoContent struct {
}

// NewDeleteConfigEndpointNoContent creates DeleteConfigEndpointNoContent with default headers values
func NewDeleteConfigEndpointNoContent() *DeleteConfigEndpointNoContent {

	return &DeleteConfigEndpointNoContent{}
}

// WriteResponse to the client
func (o *DeleteConfigEndpointNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteConfigEndpointBadRequestCode is the HTTP code returned for type DeleteConfigEndpointBadRequest
const DeleteConfigEndpointBadRequestCode int = 400

/*
DeleteConfigEndpointBadRequest Malformed arguments for API call

swagger:response deleteConfigEndpointBadRequest
*/
type DeleteConfigEndpointBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigEndpointBadRequest creates DeleteConfigEndpointBadRequest with default headers values
func NewDeleteConfigEndpointBadRequest() *DeleteConfigEndpointBadRequest {

	return &DeleteConfigEndpointBadRequest{}
}

// WithPayload adds the payload to the delete config endpoint bad request response
func (o *DeleteConfigEndpointBadRequest) WithPayload(payload *models.Error) *DeleteConfigEndpointBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config endpoint bad request response
func (o *DeleteConfigEndpointBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigEndpointBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigEndpointUnauthorizedCode is the HTTP code returned for type DeleteConfigEndpointUnauthorized
const DeleteConfigEndpointUnauthorizedCode int = 401

/*
DeleteConfigEndpointUnauthorized Invalid authentication credentials

swagger:response deleteConfigEndpointUnauthorized
*/
type DeleteConfigEndpointUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigEndpointUnauthorized creates DeleteConfigEndpointUnauthorized with default headers values
func NewDeleteConfigEndpointUnauthorized() *DeleteConfigEndpointUnauthorized {

	return &DeleteConfigEndpointUnauthorized{}
}

// WithPayload adds the payload to the delete config endpoint unauthorized response
func (o *DeleteConfigEndpointUnauthorized) WithPayload(payload *models.Error) *DeleteConfigEndpointUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config endpoint unauthorized response
func (o *DeleteConfigEndpointUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigEndpointUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigEndpointForbiddenCode is the HTTP code returned for type DeleteConfigEndpointForbidden
const DeleteConfigEndpointForbiddenCode int = 403

/*
DeleteConfigEndpointForbidden Capacity insufficient

swagger:response deleteConfigEndpointForbidden
*/
type DeleteConfigEndpointForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigEndpointForbidden creates DeleteConfigEndpointForbidden with default headers values
func NewDeleteConfigEndpointForbidden() *DeleteConfigEndpointForbidden {

	return &DeleteConfigEndpointForbidden{}
}

// WithPayload adds the payload to the delete config endpoint forbidden response
func (o *DeleteConfigEndpointForbidden) WithPayload(payload *models.Error) *DeleteConfigEndpointForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config endpoint forbidden response
func (o *DeleteConfigEndpointForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigEndpointForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigEndpointNotFoundCode is the HTTP code returned for type DeleteConfigEndpointNotFound
const DeleteConfigEndpointNotFoundCode int = 404

/*
DeleteConfigEndpointNotFound Resource not found

swagger:response deleteConfigEndpointNotFound
*/
type DeleteConfigEndpointNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigEndpointNotFound creates DeleteConfigEndpointNotFound with default headers values
func NewDeleteConfigEndpointNotFound() *DeleteConfigEndpointNotFound {

	return &DeleteConfigEndpointNotFound{}
}

// WithPayload adds the payload to the delete config endpoint not found response
func (o *DeleteConfigEndpointNotFound) WithPayload(payload *models.Error) *DeleteConfigEndpointNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config endpoint not found response
func (o *DeleteConfigEndpointNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigEndpointNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigEndpointConflictCode is the HTTP code returned for type DeleteConfigEndpointConflict
const DeleteConfigEndpointConflictCode int = 409

/*
DeleteConfigEndpointConflict Resource Conflict. VLAN already exists OR dependency VRF/VNET not found

swagger:response deleteConfigEndpointConflict
*/
type DeleteConfigEndpointConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigEndpointConflict creates DeleteConfigEndpointConflict with default headers values
func NewDeleteConfigEndpointConflict() *DeleteConfigEndpointConflict {

	return &DeleteConfigEndpointConflict{}
}

// WithPayload adds the payload to the delete config endpoint conflict response
func (o *DeleteConfigEndpointConflict) WithPayload(payload *models.Error) *DeleteConfigEndpointConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config endpoint conflict response
func (o *DeleteConfigEndpointConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigEndpointConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigEndpointInternalServerErrorCode is the HTTP code returned for type DeleteConfigEndpointInternalServerError
const DeleteConfigEndpointInternalServerErrorCode int = 500

/*
DeleteConfigEndpointInternalServerError Internal service error

swagger:response deleteConfigEndpointInternalServerError
*/
type DeleteConfigEndpointInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigEndpointInternalServerError creates DeleteConfigEndpointInternalServerError with default headers values
func NewDeleteConfigEndpointInternalServerError() *DeleteConfigEndpointInternalServerError {

	return &DeleteConfigEndpointInternalServerError{}
}

// WithPayload adds the payload to the delete config endpoint internal server error response
func (o *DeleteConfigEndpointInternalServerError) WithPayload(payload *models.Error) *DeleteConfigEndpointInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config endpoint internal server error response
func (o *DeleteConfigEndpointInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigEndpointInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigEndpointServiceUnavailableCode is the HTTP code returned for type DeleteConfigEndpointServiceUnavailable
const DeleteConfigEndpointServiceUnavailableCode int = 503

/*
DeleteConfigEndpointServiceUnavailable Maintanence mode

swagger:response deleteConfigEndpointServiceUnavailable
*/
type DeleteConfigEndpointServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigEndpointServiceUnavailable creates DeleteConfigEndpointServiceUnavailable with default headers values
func NewDeleteConfigEndpointServiceUnavailable() *DeleteConfigEndpointServiceUnavailable {

	return &DeleteConfigEndpointServiceUnavailable{}
}

// WithPayload adds the payload to the delete config endpoint service unavailable response
func (o *DeleteConfigEndpointServiceUnavailable) WithPayload(payload *models.Error) *DeleteConfigEndpointServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config endpoint service unavailable response
func (o *DeleteConfigEndpointServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigEndpointServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
