// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"
)

// DeleteConfigIpv4addressIPAddressDevIfNameURL generates an URL for the delete config ipv4address IP address dev if name operation
type DeleteConfigIpv4addressIPAddressDevIfNameURL struct {
	IfName    string
	IPAddress string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *DeleteConfigIpv4addressIPAddressDevIfNameURL) WithBasePath(bp string) *DeleteConfigIpv4addressIPAddressDevIfNameURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *DeleteConfigIpv4addressIPAddressDevIfNameURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *DeleteConfigIpv4addressIPAddressDevIfNameURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/config/ipv4address/{ip_address}/dev/{if_name}"

	ifName := o.IfName
	if ifName != "" {
		_path = strings.Replace(_path, "{if_name}", ifName, -1)
	} else {
		return nil, errors.New("ifName is required on DeleteConfigIpv4addressIPAddressDevIfNameURL")
	}

	iPAddress := o.IPAddress
	if iPAddress != "" {
		_path = strings.Replace(_path, "{ip_address}", iPAddress, -1)
	} else {
		return nil, errors.New("ipAddress is required on DeleteConfigIpv4addressIPAddressDevIfNameURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/netlox/v1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *DeleteConfigIpv4addressIPAddressDevIfNameURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *DeleteConfigIpv4addressIPAddressDevIfNameURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *DeleteConfigIpv4addressIPAddressDevIfNameURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on DeleteConfigIpv4addressIPAddressDevIfNameURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on DeleteConfigIpv4addressIPAddressDevIfNameURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *DeleteConfigIpv4addressIPAddressDevIfNameURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
