// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteConfigEndpointNameNameEpipaddressIPAddressProbetypeProbeTypeProbeportProbePortParams creates a new DeleteConfigEndpointNameNameEpipaddressIPAddressProbetypeProbeTypeProbeportProbePortParams object
//
// There are no default values defined in the spec.
func NewDeleteConfigEndpointNameNameEpipaddressIPAddressProbetypeProbeTypeProbeportProbePortParams() DeleteConfigEndpointNameNameEpipaddressIPAddressProbetypeProbeTypeProbeportProbePortParams {

	return DeleteConfigEndpointNameNameEpipaddressIPAddressProbetypeProbeTypeProbeportProbePortParams{}
}

// DeleteConfigEndpointNameNameEpipaddressIPAddressProbetypeProbeTypeProbeportProbePortParams contains all the bound params for the delete config endpoint name name epipaddress IP address probetype probe type probeport probe port operation
// typically these are obtained from a http.Request
//
// swagger:parameters DeleteConfigEndpointNameNameEpipaddressIPAddressProbetypeProbeTypeProbeportProbePort
type DeleteConfigEndpointNameNameEpipaddressIPAddressProbetypeProbeTypeProbeportProbePortParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Endpoint IP address in CIDR
	  Required: true
	  In: path
	*/
	IPAddress string
	/*Endpoint Identifier
	  Required: true
	  In: path
	*/
	Name string
	/*port on which probing has to done
	  Required: true
	  In: path
	*/
	ProbePort float64
	/*protocol type for probing
	  Required: true
	  In: path
	*/
	ProbeType string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteConfigEndpointNameNameEpipaddressIPAddressProbetypeProbeTypeProbeportProbePortParams() beforehand.
func (o *DeleteConfigEndpointNameNameEpipaddressIPAddressProbetypeProbeTypeProbeportProbePortParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rIPAddress, rhkIPAddress, _ := route.Params.GetOK("ip_address")
	if err := o.bindIPAddress(rIPAddress, rhkIPAddress, route.Formats); err != nil {
		res = append(res, err)
	}

	rName, rhkName, _ := route.Params.GetOK("name")
	if err := o.bindName(rName, rhkName, route.Formats); err != nil {
		res = append(res, err)
	}

	rProbePort, rhkProbePort, _ := route.Params.GetOK("probe_port")
	if err := o.bindProbePort(rProbePort, rhkProbePort, route.Formats); err != nil {
		res = append(res, err)
	}

	rProbeType, rhkProbeType, _ := route.Params.GetOK("probe_type")
	if err := o.bindProbeType(rProbeType, rhkProbeType, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindIPAddress binds and validates parameter IPAddress from path.
func (o *DeleteConfigEndpointNameNameEpipaddressIPAddressProbetypeProbeTypeProbeportProbePortParams) bindIPAddress(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.IPAddress = raw

	return nil
}

// bindName binds and validates parameter Name from path.
func (o *DeleteConfigEndpointNameNameEpipaddressIPAddressProbetypeProbeTypeProbeportProbePortParams) bindName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Name = raw

	return nil
}

// bindProbePort binds and validates parameter ProbePort from path.
func (o *DeleteConfigEndpointNameNameEpipaddressIPAddressProbetypeProbeTypeProbeportProbePortParams) bindProbePort(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertFloat64(raw)
	if err != nil {
		return errors.InvalidType("probe_port", "path", "float64", raw)
	}
	o.ProbePort = value

	return nil
}

// bindProbeType binds and validates parameter ProbeType from path.
func (o *DeleteConfigEndpointNameNameEpipaddressIPAddressProbetypeProbeTypeProbeportProbePortParams) bindProbeType(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.ProbeType = raw

	return nil
}
