// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewDeleteConfigIpv4addressIPAddressMaskDevIfNameParams creates a new DeleteConfigIpv4addressIPAddressMaskDevIfNameParams object
//
// There are no default values defined in the spec.
func NewDeleteConfigIpv4addressIPAddressMaskDevIfNameParams() DeleteConfigIpv4addressIPAddressMaskDevIfNameParams {

	return DeleteConfigIpv4addressIPAddressMaskDevIfNameParams{}
}

// DeleteConfigIpv4addressIPAddressMaskDevIfNameParams contains all the bound params for the delete config ipv4address IP address mask dev if name operation
// typically these are obtained from a http.Request
//
// swagger:parameters DeleteConfigIpv4addressIPAddressMaskDevIfName
type DeleteConfigIpv4addressIPAddressMaskDevIfNameParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Attributes of the target device
	  Required: true
	  In: path
	*/
	IfName string
	/*Attributes IPv4 Address in the device
	  Required: true
	  In: path
	*/
	IPAddress string
	/*Attributes IPv4 mask in the device
	  Required: true
	  In: path
	*/
	Mask string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteConfigIpv4addressIPAddressMaskDevIfNameParams() beforehand.
func (o *DeleteConfigIpv4addressIPAddressMaskDevIfNameParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rIfName, rhkIfName, _ := route.Params.GetOK("if_name")
	if err := o.bindIfName(rIfName, rhkIfName, route.Formats); err != nil {
		res = append(res, err)
	}

	rIPAddress, rhkIPAddress, _ := route.Params.GetOK("ip_address")
	if err := o.bindIPAddress(rIPAddress, rhkIPAddress, route.Formats); err != nil {
		res = append(res, err)
	}

	rMask, rhkMask, _ := route.Params.GetOK("mask")
	if err := o.bindMask(rMask, rhkMask, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindIfName binds and validates parameter IfName from path.
func (o *DeleteConfigIpv4addressIPAddressMaskDevIfNameParams) bindIfName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.IfName = raw

	return nil
}

// bindIPAddress binds and validates parameter IPAddress from path.
func (o *DeleteConfigIpv4addressIPAddressMaskDevIfNameParams) bindIPAddress(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.IPAddress = raw

	return nil
}

// bindMask binds and validates parameter Mask from path.
func (o *DeleteConfigIpv4addressIPAddressMaskDevIfNameParams) bindMask(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Mask = raw

	return nil
}
