// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// GetConfigExportOKCode is the HTTP code returned for type GetConfigExportOK
const GetConfigExportOKCode int = 200

/*
GetConfigExportOK Configuration JSON file download

swagger:response getConfigExportOK
*/
type GetConfigExportOK struct {

	/*
	  In: Body
	*/
	Payload io.ReadCloser `json:"body,omitempty"`
}

// NewGetConfigExportOK creates GetConfigExportOK with default headers values
func NewGetConfigExportOK() *GetConfigExportOK {

	return &GetConfigExportOK{}
}

// WithPayload adds the payload to the get config export o k response
func (o *GetConfigExportOK) WithPayload(payload io.ReadCloser) *GetConfigExportOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config export o k response
func (o *GetConfigExportOK) SetPayload(payload io.ReadCloser) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigExportOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetConfigExportBadRequestCode is the HTTP code returned for type GetConfigExportBadRequest
const GetConfigExportBadRequestCode int = 400

/*
GetConfigExportBadRequest Invalid parameters

swagger:response getConfigExportBadRequest
*/
type GetConfigExportBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigExportBadRequest creates GetConfigExportBadRequest with default headers values
func NewGetConfigExportBadRequest() *GetConfigExportBadRequest {

	return &GetConfigExportBadRequest{}
}

// WithPayload adds the payload to the get config export bad request response
func (o *GetConfigExportBadRequest) WithPayload(payload *models.Error) *GetConfigExportBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config export bad request response
func (o *GetConfigExportBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigExportBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigExportUnauthorizedCode is the HTTP code returned for type GetConfigExportUnauthorized
const GetConfigExportUnauthorizedCode int = 401

/*
GetConfigExportUnauthorized Invalid authentication credentials

swagger:response getConfigExportUnauthorized
*/
type GetConfigExportUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigExportUnauthorized creates GetConfigExportUnauthorized with default headers values
func NewGetConfigExportUnauthorized() *GetConfigExportUnauthorized {

	return &GetConfigExportUnauthorized{}
}

// WithPayload adds the payload to the get config export unauthorized response
func (o *GetConfigExportUnauthorized) WithPayload(payload *models.Error) *GetConfigExportUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config export unauthorized response
func (o *GetConfigExportUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigExportUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigExportInternalServerErrorCode is the HTTP code returned for type GetConfigExportInternalServerError
const GetConfigExportInternalServerErrorCode int = 500

/*
GetConfigExportInternalServerError Internal service error

swagger:response getConfigExportInternalServerError
*/
type GetConfigExportInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigExportInternalServerError creates GetConfigExportInternalServerError with default headers values
func NewGetConfigExportInternalServerError() *GetConfigExportInternalServerError {

	return &GetConfigExportInternalServerError{}
}

// WithPayload adds the payload to the get config export internal server error response
func (o *GetConfigExportInternalServerError) WithPayload(payload *models.Error) *GetConfigExportInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config export internal server error response
func (o *GetConfigExportInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigExportInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigExportServiceUnavailableCode is the HTTP code returned for type GetConfigExportServiceUnavailable
const GetConfigExportServiceUnavailableCode int = 503

/*
GetConfigExportServiceUnavailable Maintenance mode

swagger:response getConfigExportServiceUnavailable
*/
type GetConfigExportServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigExportServiceUnavailable creates GetConfigExportServiceUnavailable with default headers values
func NewGetConfigExportServiceUnavailable() *GetConfigExportServiceUnavailable {

	return &GetConfigExportServiceUnavailable{}
}

// WithPayload adds the payload to the get config export service unavailable response
func (o *GetConfigExportServiceUnavailable) WithPayload(payload *models.Error) *GetConfigExportServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config export service unavailable response
func (o *GetConfigExportServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigExportServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
