// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetLogArchivesHandlerFunc turns a function with the right signature into a get log archives handler
type GetLogArchivesHandlerFunc func(GetLogArchivesParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetLogArchivesHandlerFunc) Handle(params GetLogArchivesParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetLogArchivesHandler interface for that can handle valid get log archives params
type GetLogArchivesHandler interface {
	Handle(GetLogArchivesParams, interface{}) middleware.Responder
}

// NewGetLogArchives creates a new http.Handler for the get log archives operation
func NewGetLogArchives(ctx *middleware.Context, handler GetLogArchivesHandler) *GetLogArchives {
	return &GetLogArchives{Context: ctx, Handler: handler}
}

/*
	GetLogArchives swagger:route GET /log-archives getLogArchives

# List available log archives

Retrieve a list of all rotated log archive files available for download.
*/
type GetLogArchives struct {
	Context *middleware.Context
	Handler GetLogArchivesHandler
}

func (o *GetLogArchives) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetLogArchivesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
