// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// GetNodegraphServiceOKCode is the HTTP code returned for type GetNodegraphServiceOK
const GetNodegraphServiceOKCode int = 200

/*
GetNodegraphServiceOK OK

swagger:response getNodegraphServiceOK
*/
type GetNodegraphServiceOK struct {

	/*
	  In: Body
	*/
	Payload *models.NodeGraphShcmea `json:"body,omitempty"`
}

// NewGetNodegraphServiceOK creates GetNodegraphServiceOK with default headers values
func NewGetNodegraphServiceOK() *GetNodegraphServiceOK {

	return &GetNodegraphServiceOK{}
}

// WithPayload adds the payload to the get nodegraph service o k response
func (o *GetNodegraphServiceOK) WithPayload(payload *models.NodeGraphShcmea) *GetNodegraphServiceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get nodegraph service o k response
func (o *GetNodegraphServiceOK) SetPayload(payload *models.NodeGraphShcmea) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNodegraphServiceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetNodegraphServiceUnauthorizedCode is the HTTP code returned for type GetNodegraphServiceUnauthorized
const GetNodegraphServiceUnauthorizedCode int = 401

/*
GetNodegraphServiceUnauthorized Invalid authentication credentials

swagger:response getNodegraphServiceUnauthorized
*/
type GetNodegraphServiceUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetNodegraphServiceUnauthorized creates GetNodegraphServiceUnauthorized with default headers values
func NewGetNodegraphServiceUnauthorized() *GetNodegraphServiceUnauthorized {

	return &GetNodegraphServiceUnauthorized{}
}

// WithPayload adds the payload to the get nodegraph service unauthorized response
func (o *GetNodegraphServiceUnauthorized) WithPayload(payload *models.Error) *GetNodegraphServiceUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get nodegraph service unauthorized response
func (o *GetNodegraphServiceUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNodegraphServiceUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetNodegraphServiceInternalServerErrorCode is the HTTP code returned for type GetNodegraphServiceInternalServerError
const GetNodegraphServiceInternalServerErrorCode int = 500

/*
GetNodegraphServiceInternalServerError Internal service error

swagger:response getNodegraphServiceInternalServerError
*/
type GetNodegraphServiceInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetNodegraphServiceInternalServerError creates GetNodegraphServiceInternalServerError with default headers values
func NewGetNodegraphServiceInternalServerError() *GetNodegraphServiceInternalServerError {

	return &GetNodegraphServiceInternalServerError{}
}

// WithPayload adds the payload to the get nodegraph service internal server error response
func (o *GetNodegraphServiceInternalServerError) WithPayload(payload *models.Error) *GetNodegraphServiceInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get nodegraph service internal server error response
func (o *GetNodegraphServiceInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNodegraphServiceInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetNodegraphServiceServiceUnavailableCode is the HTTP code returned for type GetNodegraphServiceServiceUnavailable
const GetNodegraphServiceServiceUnavailableCode int = 503

/*
GetNodegraphServiceServiceUnavailable Maintenance mode

swagger:response getNodegraphServiceServiceUnavailable
*/
type GetNodegraphServiceServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetNodegraphServiceServiceUnavailable creates GetNodegraphServiceServiceUnavailable with default headers values
func NewGetNodegraphServiceServiceUnavailable() *GetNodegraphServiceServiceUnavailable {

	return &GetNodegraphServiceServiceUnavailable{}
}

// WithPayload adds the payload to the get nodegraph service service unavailable response
func (o *GetNodegraphServiceServiceUnavailable) WithPayload(payload *models.Error) *GetNodegraphServiceServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get nodegraph service service unavailable response
func (o *GetNodegraphServiceServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetNodegraphServiceServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
