// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// GetMetricsLbprocessedtrafficOKCode is the HTTP code returned for type GetMetricsLbprocessedtrafficOK
const GetMetricsLbprocessedtrafficOKCode int = 200

/*
GetMetricsLbprocessedtrafficOK OK

swagger:response getMetricsLbprocessedtrafficOK
*/
type GetMetricsLbprocessedtrafficOK struct {

	/*
	  In: Body
	*/
	Payload *models.LbProcessedTrafficMetrics `json:"body,omitempty"`
}

// NewGetMetricsLbprocessedtrafficOK creates GetMetricsLbprocessedtrafficOK with default headers values
func NewGetMetricsLbprocessedtrafficOK() *GetMetricsLbprocessedtrafficOK {

	return &GetMetricsLbprocessedtrafficOK{}
}

// WithPayload adds the payload to the get metrics lbprocessedtraffic o k response
func (o *GetMetricsLbprocessedtrafficOK) WithPayload(payload *models.LbProcessedTrafficMetrics) *GetMetricsLbprocessedtrafficOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get metrics lbprocessedtraffic o k response
func (o *GetMetricsLbprocessedtrafficOK) SetPayload(payload *models.LbProcessedTrafficMetrics) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMetricsLbprocessedtrafficOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetMetricsLbprocessedtrafficInternalServerErrorCode is the HTTP code returned for type GetMetricsLbprocessedtrafficInternalServerError
const GetMetricsLbprocessedtrafficInternalServerErrorCode int = 500

/*
GetMetricsLbprocessedtrafficInternalServerError Internal service error

swagger:response getMetricsLbprocessedtrafficInternalServerError
*/
type GetMetricsLbprocessedtrafficInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetMetricsLbprocessedtrafficInternalServerError creates GetMetricsLbprocessedtrafficInternalServerError with default headers values
func NewGetMetricsLbprocessedtrafficInternalServerError() *GetMetricsLbprocessedtrafficInternalServerError {

	return &GetMetricsLbprocessedtrafficInternalServerError{}
}

// WithPayload adds the payload to the get metrics lbprocessedtraffic internal server error response
func (o *GetMetricsLbprocessedtrafficInternalServerError) WithPayload(payload *models.Error) *GetMetricsLbprocessedtrafficInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get metrics lbprocessedtraffic internal server error response
func (o *GetMetricsLbprocessedtrafficInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMetricsLbprocessedtrafficInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
