// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// GetConfigMetricsOKCode is the HTTP code returned for type GetConfigMetricsOK
const GetConfigMetricsOKCode int = 200

/*
GetConfigMetricsOK prometheus config value

swagger:response getConfigMetricsOK
*/
type GetConfigMetricsOK struct {

	/*
	  In: Body
	*/
	Payload *models.MetricsConfig `json:"body,omitempty"`
}

// NewGetConfigMetricsOK creates GetConfigMetricsOK with default headers values
func NewGetConfigMetricsOK() *GetConfigMetricsOK {

	return &GetConfigMetricsOK{}
}

// WithPayload adds the payload to the get config metrics o k response
func (o *GetConfigMetricsOK) WithPayload(payload *models.MetricsConfig) *GetConfigMetricsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config metrics o k response
func (o *GetConfigMetricsOK) SetPayload(payload *models.MetricsConfig) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigMetricsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigMetricsBadRequestCode is the HTTP code returned for type GetConfigMetricsBadRequest
const GetConfigMetricsBadRequestCode int = 400

/*
GetConfigMetricsBadRequest Malformed arguments for API call

swagger:response getConfigMetricsBadRequest
*/
type GetConfigMetricsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigMetricsBadRequest creates GetConfigMetricsBadRequest with default headers values
func NewGetConfigMetricsBadRequest() *GetConfigMetricsBadRequest {

	return &GetConfigMetricsBadRequest{}
}

// WithPayload adds the payload to the get config metrics bad request response
func (o *GetConfigMetricsBadRequest) WithPayload(payload *models.Error) *GetConfigMetricsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config metrics bad request response
func (o *GetConfigMetricsBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigMetricsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigMetricsUnauthorizedCode is the HTTP code returned for type GetConfigMetricsUnauthorized
const GetConfigMetricsUnauthorizedCode int = 401

/*
GetConfigMetricsUnauthorized Invalid authentication credentials

swagger:response getConfigMetricsUnauthorized
*/
type GetConfigMetricsUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigMetricsUnauthorized creates GetConfigMetricsUnauthorized with default headers values
func NewGetConfigMetricsUnauthorized() *GetConfigMetricsUnauthorized {

	return &GetConfigMetricsUnauthorized{}
}

// WithPayload adds the payload to the get config metrics unauthorized response
func (o *GetConfigMetricsUnauthorized) WithPayload(payload *models.Error) *GetConfigMetricsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config metrics unauthorized response
func (o *GetConfigMetricsUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigMetricsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigMetricsInternalServerErrorCode is the HTTP code returned for type GetConfigMetricsInternalServerError
const GetConfigMetricsInternalServerErrorCode int = 500

/*
GetConfigMetricsInternalServerError Internal service error

swagger:response getConfigMetricsInternalServerError
*/
type GetConfigMetricsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigMetricsInternalServerError creates GetConfigMetricsInternalServerError with default headers values
func NewGetConfigMetricsInternalServerError() *GetConfigMetricsInternalServerError {

	return &GetConfigMetricsInternalServerError{}
}

// WithPayload adds the payload to the get config metrics internal server error response
func (o *GetConfigMetricsInternalServerError) WithPayload(payload *models.Error) *GetConfigMetricsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config metrics internal server error response
func (o *GetConfigMetricsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigMetricsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigMetricsServiceUnavailableCode is the HTTP code returned for type GetConfigMetricsServiceUnavailable
const GetConfigMetricsServiceUnavailableCode int = 503

/*
GetConfigMetricsServiceUnavailable Maintenance mode

swagger:response getConfigMetricsServiceUnavailable
*/
type GetConfigMetricsServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigMetricsServiceUnavailable creates GetConfigMetricsServiceUnavailable with default headers values
func NewGetConfigMetricsServiceUnavailable() *GetConfigMetricsServiceUnavailable {

	return &GetConfigMetricsServiceUnavailable{}
}

// WithPayload adds the payload to the get config metrics service unavailable response
func (o *GetConfigMetricsServiceUnavailable) WithPayload(payload *models.Error) *GetConfigMetricsServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config metrics service unavailable response
func (o *GetConfigMetricsServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigMetricsServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
