// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/loxilb-io/loxilb/api/models"
)

// GetConfigBgpPolicyDefinitionsAllHandlerFunc turns a function with the right signature into a get config bgp policy definitions all handler
type GetConfigBgpPolicyDefinitionsAllHandlerFunc func(GetConfigBgpPolicyDefinitionsAllParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetConfigBgpPolicyDefinitionsAllHandlerFunc) Handle(params GetConfigBgpPolicyDefinitionsAllParams) middleware.Responder {
	return fn(params)
}

// GetConfigBgpPolicyDefinitionsAllHandler interface for that can handle valid get config bgp policy definitions all params
type GetConfigBgpPolicyDefinitionsAllHandler interface {
	Handle(GetConfigBgpPolicyDefinitionsAllParams) middleware.Responder
}

// NewGetConfigBgpPolicyDefinitionsAll creates a new http.Handler for the get config bgp policy definitions all operation
func NewGetConfigBgpPolicyDefinitionsAll(ctx *middleware.Context, handler GetConfigBgpPolicyDefinitionsAllHandler) *GetConfigBgpPolicyDefinitionsAll {
	return &GetConfigBgpPolicyDefinitionsAll{Context: ctx, Handler: handler}
}

/*
	GetConfigBgpPolicyDefinitionsAll swagger:route GET /config/bgp/policy/definitions/all getConfigBgpPolicyDefinitionsAll

# Get BGP Policy definitions

Get BGP Policy definitions
*/
type GetConfigBgpPolicyDefinitionsAll struct {
	Context *middleware.Context
	Handler GetConfigBgpPolicyDefinitionsAllHandler
}

func (o *GetConfigBgpPolicyDefinitionsAll) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetConfigBgpPolicyDefinitionsAllParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetConfigBgpPolicyDefinitionsAllOKBody get config bgp policy definitions all o k body
//
// swagger:model GetConfigBgpPolicyDefinitionsAllOKBody
type GetConfigBgpPolicyDefinitionsAllOKBody struct {

	// bgp policy attr
	BgpPolicyAttr []*models.BGPPolicyDefinitionsMod `json:"bgpPolicyAttr"`
}

// Validate validates this get config bgp policy definitions all o k body
func (o *GetConfigBgpPolicyDefinitionsAllOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateBgpPolicyAttr(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetConfigBgpPolicyDefinitionsAllOKBody) validateBgpPolicyAttr(formats strfmt.Registry) error {
	if swag.IsZero(o.BgpPolicyAttr) { // not required
		return nil
	}

	for i := 0; i < len(o.BgpPolicyAttr); i++ {
		if swag.IsZero(o.BgpPolicyAttr[i]) { // not required
			continue
		}

		if o.BgpPolicyAttr[i] != nil {
			if err := o.BgpPolicyAttr[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getConfigBgpPolicyDefinitionsAllOK" + "." + "bgpPolicyAttr" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getConfigBgpPolicyDefinitionsAllOK" + "." + "bgpPolicyAttr" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get config bgp policy definitions all o k body based on the context it is used
func (o *GetConfigBgpPolicyDefinitionsAllOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateBgpPolicyAttr(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetConfigBgpPolicyDefinitionsAllOKBody) contextValidateBgpPolicyAttr(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.BgpPolicyAttr); i++ {

		if o.BgpPolicyAttr[i] != nil {
			if err := o.BgpPolicyAttr[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getConfigBgpPolicyDefinitionsAllOK" + "." + "bgpPolicyAttr" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getConfigBgpPolicyDefinitionsAllOK" + "." + "bgpPolicyAttr" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetConfigBgpPolicyDefinitionsAllOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetConfigBgpPolicyDefinitionsAllOKBody) UnmarshalBinary(b []byte) error {
	var res GetConfigBgpPolicyDefinitionsAllOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
