// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetNodegraphServiceParams creates a new GetNodegraphServiceParams object
//
// There are no default values defined in the spec.
func NewGetNodegraphServiceParams() GetNodegraphServiceParams {

	return GetNodegraphServiceParams{}
}

// GetNodegraphServiceParams contains all the bound params for the get nodegraph service operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetNodegraphService
type GetNodegraphServiceParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Name of the service to filter the topology by.
	  Required: true
	  In: path
	*/
	Service string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetNodegraphServiceParams() beforehand.
func (o *GetNodegraphServiceParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rService, rhkService, _ := route.Params.GetOK("service")
	if err := o.bindService(rService, rhkService, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindService binds and validates parameter Service from path.
func (o *GetNodegraphServiceParams) bindService(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Service = raw

	return nil
}
