// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// GetMetricsFwdropsOKCode is the HTTP code returned for type GetMetricsFwdropsOK
const GetMetricsFwdropsOKCode int = 200

/*
GetMetricsFwdropsOK OK

swagger:response getMetricsFwdropsOK
*/
type GetMetricsFwdropsOK struct {

	/*
	  In: Body
	*/
	Payload *models.FwDropsMetrics `json:"body,omitempty"`
}

// NewGetMetricsFwdropsOK creates GetMetricsFwdropsOK with default headers values
func NewGetMetricsFwdropsOK() *GetMetricsFwdropsOK {

	return &GetMetricsFwdropsOK{}
}

// WithPayload adds the payload to the get metrics fwdrops o k response
func (o *GetMetricsFwdropsOK) WithPayload(payload *models.FwDropsMetrics) *GetMetricsFwdropsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get metrics fwdrops o k response
func (o *GetMetricsFwdropsOK) SetPayload(payload *models.FwDropsMetrics) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMetricsFwdropsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetMetricsFwdropsInternalServerErrorCode is the HTTP code returned for type GetMetricsFwdropsInternalServerError
const GetMetricsFwdropsInternalServerErrorCode int = 500

/*
GetMetricsFwdropsInternalServerError Internal service error

swagger:response getMetricsFwdropsInternalServerError
*/
type GetMetricsFwdropsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetMetricsFwdropsInternalServerError creates GetMetricsFwdropsInternalServerError with default headers values
func NewGetMetricsFwdropsInternalServerError() *GetMetricsFwdropsInternalServerError {

	return &GetMetricsFwdropsInternalServerError{}
}

// WithPayload adds the payload to the get metrics fwdrops internal server error response
func (o *GetMetricsFwdropsInternalServerError) WithPayload(payload *models.Error) *GetMetricsFwdropsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get metrics fwdrops internal server error response
func (o *GetMetricsFwdropsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMetricsFwdropsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
