// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostConfigSessionHandlerFunc turns a function with the right signature into a post config session handler
type PostConfigSessionHandlerFunc func(PostConfigSessionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostConfigSessionHandlerFunc) Handle(params PostConfigSessionParams) middleware.Responder {
	return fn(params)
}

// PostConfigSessionHandler interface for that can handle valid post config session params
type PostConfigSessionHandler interface {
	Handle(PostConfigSessionParams) middleware.Responder
}

// NewPostConfigSession creates a new http.Handler for the post config session operation
func NewPostConfigSession(ctx *middleware.Context, handler PostConfigSessionHandler) *PostConfigSession {
	return &PostConfigSession{Context: ctx, Handler: handler}
}

/*
	PostConfigSession swagger:route POST /config/session postConfigSession

# Create a new session config

Create a new session config for 5G.
*/
type PostConfigSession struct {
	Context *middleware.Context
	Handler PostConfigSessionHandler
}

func (o *PostConfigSession) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostConfigSessionParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
