// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"mime/multipart"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
)

// PostConfigImportMaxParseMemory sets the maximum size in bytes for
// the multipart form parser for this operation.
//
// The default value is 32 MB.
// The multipart parser stores up to this + 10MB.
var PostConfigImportMaxParseMemory int64 = 32 << 20

// NewPostConfigImportParams creates a new PostConfigImportParams object
//
// There are no default values defined in the spec.
func NewPostConfigImportParams() PostConfigImportParams {

	return PostConfigImportParams{}
}

// PostConfigImportParams contains all the bound params for the post config import operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostConfigImport
type PostConfigImportParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The configuration file to upload.
	  In: formData
	*/
	Configuration io.ReadCloser
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostConfigImportParams() beforehand.
func (o *PostConfigImportParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := r.ParseMultipartForm(PostConfigImportMaxParseMemory); err != nil {
		if err != http.ErrNotMultipart {
			return errors.New(400, "%v", err)
		} else if err := r.ParseForm(); err != nil {
			return errors.New(400, "%v", err)
		}
	}

	configuration, configurationHeader, err := r.FormFile("configuration")
	if err != nil && err != http.ErrMissingFile {
		res = append(res, errors.New(400, "reading file %q failed: %v", "configuration", err))
	} else if err == http.ErrMissingFile {
		// no-op for missing but optional file parameter
	} else if err := o.bindConfiguration(configuration, configurationHeader); err != nil {
		res = append(res, err)
	} else {
		o.Configuration = &runtime.File{Data: configuration, Header: configurationHeader}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindConfiguration binds file parameter Configuration.
//
// The only supported validations on files are MinLength and MaxLength
func (o *PostConfigImportParams) bindConfiguration(file multipart.File, header *multipart.FileHeader) error {
	return nil
}
