// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostConfigFirewallHandlerFunc turns a function with the right signature into a post config firewall handler
type PostConfigFirewallHandlerFunc func(PostConfigFirewallParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostConfigFirewallHandlerFunc) Handle(params PostConfigFirewallParams) middleware.Responder {
	return fn(params)
}

// PostConfigFirewallHandler interface for that can handle valid post config firewall params
type PostConfigFirewallHandler interface {
	Handle(PostConfigFirewallParams) middleware.Responder
}

// NewPostConfigFirewall creates a new http.Handler for the post config firewall operation
func NewPostConfigFirewall(ctx *middleware.Context, handler PostConfigFirewallHandler) *PostConfigFirewall {
	return &PostConfigFirewall{Context: ctx, Handler: handler}
}

/*
	PostConfigFirewall swagger:route POST /config/firewall postConfigFirewall

# Create a new firewall config

Create a new firewall config for security.
*/
type PostConfigFirewall struct {
	Context *middleware.Context
	Handler PostConfigFirewallHandler
}

func (o *PostConfigFirewall) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostConfigFirewallParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
