// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostConfigCorsHandlerFunc turns a function with the right signature into a post config cors handler
type PostConfigCorsHandlerFunc func(PostConfigCorsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostConfigCorsHandlerFunc) Handle(params PostConfigCorsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostConfigCorsHandler interface for that can handle valid post config cors params
type PostConfigCorsHandler interface {
	Handle(PostConfigCorsParams, interface{}) middleware.Responder
}

// NewPostConfigCors creates a new http.Handler for the post config cors operation
func NewPostConfigCors(ctx *middleware.Context, handler PostConfigCorsHandler) *PostConfigCors {
	return &PostConfigCors{Context: ctx, Handler: handler}
}

/*
	PostConfigCors swagger:route POST /config/cors postConfigCors

Post full K8s metadata set (Pod, Service, Endpoint, Node, Namespace)

Post full K8s metadata set (Pod, Service, Endpoint, Node, Namespace)
*/
type PostConfigCors struct {
	Context *middleware.Context
	Handler PostConfigCorsHandler
}

func (o *PostConfigCors) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostConfigCorsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
