// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostConfigEndpointhoststateHandlerFunc turns a function with the right signature into a post config endpointhoststate handler
type PostConfigEndpointhoststateHandlerFunc func(PostConfigEndpointhoststateParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostConfigEndpointhoststateHandlerFunc) Handle(params PostConfigEndpointhoststateParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostConfigEndpointhoststateHandler interface for that can handle valid post config endpointhoststate params
type PostConfigEndpointhoststateHandler interface {
	Handle(PostConfigEndpointhoststateParams, interface{}) middleware.Responder
}

// NewPostConfigEndpointhoststate creates a new http.Handler for the post config endpointhoststate operation
func NewPostConfigEndpointhoststate(ctx *middleware.Context, handler PostConfigEndpointhoststateHandler) *PostConfigEndpointhoststate {
	return &PostConfigEndpointhoststate{Context: ctx, Handler: handler}
}

/*
	PostConfigEndpointhoststate swagger:route POST /config/endpointhoststate postConfigEndpointhoststate

# Sets the state of a host

Sets the state of a host which can have multiple endpoints
*/
type PostConfigEndpointhoststate struct {
	Context *middleware.Context
	Handler PostConfigEndpointhoststateHandler
}

func (o *PostConfigEndpointhoststate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostConfigEndpointhoststateParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
