apiVersion: v1
kind: Service
metadata:
  name: udp-onearm-svc
  annotations:
   loxilb.io/liveness: "yes"
   loxilb.io/lbmode: "onearm"
spec:
  externalTrafficPolicy: Local
  loadBalancerClass: loxilb.io/loxilb
  selector:
    what: udp-onearm-test
  ports:
    - port: 55002
      protocol: UDP
      targetPort: 33333
  type: LoadBalancer
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: udp-onearm-ds
  labels:
    what: udp-onearm-test
spec:
  selector:
    matchLabels:
      what: udp-onearm-test
  template:
    metadata:
      labels:
        what: udp-onearm-test
    spec:
      containers:
      - name: udp-onearm-test
        image: ghcr.io/loxilb-io/udp-echo:latest
        ports:
        - containerPort: 33333
