apiVersion: v1
kind: Pod
metadata:
  name: pod-02
  labels:
    app: pod-02
  #annotations:
  #  k8s.v1.cni.cncf.io/networks: vlan5
spec:
  containers:
    - name: nginx
      image: ghcr.io/nicolaka/netshoot:latest
      command:
        - sleep
        - "infinity"
      ports:
        - containerPort: 80
      securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
