# -*- mode: ruby -*-
# vi: set ft=ruby :

loxilbs = (ENV['LOXILBS'] || "1").to_i
eps = (ENV['LOXILBS'] || "1").to_i
box_name = (ENV['VAGRANT_BOX'] || "sysnet4admin/Ubuntu-k8s")
box_version = "0.7.1"
Vagrant.configure("2") do |config|
  config.vm.box = "#{box_name}"
  config.vm.box_version = "#{box_version}"

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  (1..loxilbs).each do |node_number|
    config.vm.define "llb#{node_number}" do |loxilb|
      loxilb.vm.hostname = "llb#{node_number}"
      ip = node_number + 245
      loxilb.vm.network :private_network, ip: "192.168.163.#{ip}", :netmask => "255.255.255.0"
      loxilb.vm.provision :shell, :path => "loxilb.sh"
      loxilb.vm.provider :virtualbox do |vbox|
        vbox.customize ["modifyvm", :id, "--memory", 16000]
        vbox.customize ["modifyvm", :id, "--cpus", 8]
        vbox.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      end
    end
  end
end
