// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetOauthProviderParams creates a new GetOauthProviderParams object
//
// There are no default values defined in the spec.
func NewGetOauthProviderParams() GetOauthProviderParams {

	return GetOauthProviderParams{}
}

// GetOauthProviderParams contains all the bound params for the get oauth provider operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetOauthProvider
type GetOauthProviderParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*OAuth provider
	  Required: true
	  In: path
	*/
	Provider string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetOauthProviderParams() beforehand.
func (o *GetOauthProviderParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rProvider, rhkProvider, _ := route.Params.GetOK("provider")
	if err := o.bindProvider(rProvider, rhkProvider, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindProvider binds and validates parameter Provider from path.
func (o *GetOauthProviderParams) bindProvider(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Provider = raw

	return nil
}
