// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetOauthProviderTokenParams creates a new GetOauthProviderTokenParams object
//
// There are no default values defined in the spec.
func NewGetOauthProviderTokenParams() GetOauthProviderTokenParams {

	return GetOauthProviderTokenParams{}
}

// GetOauthProviderTokenParams contains all the bound params for the get oauth provider token operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetOauthProviderToken
type GetOauthProviderTokenParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*OAuth provider
	  Required: true
	  In: path
	*/
	Provider string
	/*OAuth refresh token
	  Required: true
	  In: query
	*/
	Refreshtoken string
	/*OAuth access token
	  Required: true
	  In: query
	*/
	Token string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetOauthProviderTokenParams() beforehand.
func (o *GetOauthProviderTokenParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	rProvider, rhkProvider, _ := route.Params.GetOK("provider")
	if err := o.bindProvider(rProvider, rhkProvider, route.Formats); err != nil {
		res = append(res, err)
	}

	qRefreshtoken, qhkRefreshtoken, _ := qs.GetOK("refreshtoken")
	if err := o.bindRefreshtoken(qRefreshtoken, qhkRefreshtoken, route.Formats); err != nil {
		res = append(res, err)
	}

	qToken, qhkToken, _ := qs.GetOK("token")
	if err := o.bindToken(qToken, qhkToken, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindProvider binds and validates parameter Provider from path.
func (o *GetOauthProviderTokenParams) bindProvider(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Provider = raw

	return nil
}

// bindRefreshtoken binds and validates parameter Refreshtoken from query.
func (o *GetOauthProviderTokenParams) bindRefreshtoken(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("refreshtoken", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("refreshtoken", "query", raw); err != nil {
		return err
	}
	o.Refreshtoken = raw

	return nil
}

// bindToken binds and validates parameter Token from query.
func (o *GetOauthProviderTokenParams) bindToken(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("token", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("token", "query", raw); err != nil {
		return err
	}
	o.Token = raw

	return nil
}
