// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetOauthProviderHandlerFunc turns a function with the right signature into a get oauth provider handler
type GetOauthProviderHandlerFunc func(GetOauthProviderParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetOauthProviderHandlerFunc) Handle(params GetOauthProviderParams) middleware.Responder {
	return fn(params)
}

// GetOauthProviderHandler interface for that can handle valid get oauth provider params
type GetOauthProviderHandler interface {
	Handle(GetOauthProviderParams) middleware.Responder
}

// NewGetOauthProvider creates a new http.Handler for the get oauth provider operation
func NewGetOauthProvider(ctx *middleware.Context, handler GetOauthProviderHandler) *GetOauthProvider {
	return &GetOauthProvider{Context: ctx, Handler: handler}
}

/*
	GetOauthProvider swagger:route GET /oauth/{provider} auth getOauthProvider

# OAuth login

Initiates the OAuth login flow for the specified provider.
*/
type GetOauthProvider struct {
	Context *middleware.Context
	Handler GetOauthProviderHandler
}

func (o *GetOauthProvider) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetOauthProviderParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
