// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// PostAuthTokenUpgradeOKCode is the HTTP code returned for type PostAuthTokenUpgradeOK
const PostAuthTokenUpgradeOKCode int = 200

/*
PostAuthTokenUpgradeOK OK

swagger:response postAuthTokenUpgradeOK
*/
type PostAuthTokenUpgradeOK struct {

	/*
	  In: Body
	*/
	Payload *models.UpdateLicenseRequest `json:"body,omitempty"`
}

// NewPostAuthTokenUpgradeOK creates PostAuthTokenUpgradeOK with default headers values
func NewPostAuthTokenUpgradeOK() *PostAuthTokenUpgradeOK {

	return &PostAuthTokenUpgradeOK{}
}

// WithPayload adds the payload to the post auth token upgrade o k response
func (o *PostAuthTokenUpgradeOK) WithPayload(payload *models.UpdateLicenseRequest) *PostAuthTokenUpgradeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post auth token upgrade o k response
func (o *PostAuthTokenUpgradeOK) SetPayload(payload *models.UpdateLicenseRequest) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAuthTokenUpgradeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAuthTokenUpgradeBadRequestCode is the HTTP code returned for type PostAuthTokenUpgradeBadRequest
const PostAuthTokenUpgradeBadRequestCode int = 400

/*
PostAuthTokenUpgradeBadRequest Bad Request

swagger:response postAuthTokenUpgradeBadRequest
*/
type PostAuthTokenUpgradeBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostAuthTokenUpgradeBadRequest creates PostAuthTokenUpgradeBadRequest with default headers values
func NewPostAuthTokenUpgradeBadRequest() *PostAuthTokenUpgradeBadRequest {

	return &PostAuthTokenUpgradeBadRequest{}
}

// WithPayload adds the payload to the post auth token upgrade bad request response
func (o *PostAuthTokenUpgradeBadRequest) WithPayload(payload *models.Error) *PostAuthTokenUpgradeBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post auth token upgrade bad request response
func (o *PostAuthTokenUpgradeBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAuthTokenUpgradeBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAuthTokenUpgradeUnauthorizedCode is the HTTP code returned for type PostAuthTokenUpgradeUnauthorized
const PostAuthTokenUpgradeUnauthorizedCode int = 401

/*
PostAuthTokenUpgradeUnauthorized Unauthorized

swagger:response postAuthTokenUpgradeUnauthorized
*/
type PostAuthTokenUpgradeUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostAuthTokenUpgradeUnauthorized creates PostAuthTokenUpgradeUnauthorized with default headers values
func NewPostAuthTokenUpgradeUnauthorized() *PostAuthTokenUpgradeUnauthorized {

	return &PostAuthTokenUpgradeUnauthorized{}
}

// WithPayload adds the payload to the post auth token upgrade unauthorized response
func (o *PostAuthTokenUpgradeUnauthorized) WithPayload(payload *models.Error) *PostAuthTokenUpgradeUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post auth token upgrade unauthorized response
func (o *PostAuthTokenUpgradeUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAuthTokenUpgradeUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAuthTokenUpgradeInternalServerErrorCode is the HTTP code returned for type PostAuthTokenUpgradeInternalServerError
const PostAuthTokenUpgradeInternalServerErrorCode int = 500

/*
PostAuthTokenUpgradeInternalServerError Internal Server Error

swagger:response postAuthTokenUpgradeInternalServerError
*/
type PostAuthTokenUpgradeInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostAuthTokenUpgradeInternalServerError creates PostAuthTokenUpgradeInternalServerError with default headers values
func NewPostAuthTokenUpgradeInternalServerError() *PostAuthTokenUpgradeInternalServerError {

	return &PostAuthTokenUpgradeInternalServerError{}
}

// WithPayload adds the payload to the post auth token upgrade internal server error response
func (o *PostAuthTokenUpgradeInternalServerError) WithPayload(payload *models.Error) *PostAuthTokenUpgradeInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post auth token upgrade internal server error response
func (o *PostAuthTokenUpgradeInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAuthTokenUpgradeInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
