#!/bin/bash
set -eo pipefail
set -x

. "$(dirname $0)/../common.sh"

set -u

threads=$1
time=$2
dst="$3"

$hexec l3ep1 \
  iperf -s -p 12865 \
  > "${dst}server.log" 2>&1 &
# $! only gives use the pid of sudo.

$hexec l3h1 \
  iperf -c 20.20.20.1 -t $time -p 12865 -P $threads \
  2>&1 | tee "${dst}client.log"

sudo pkill -SIGTERM iperf
wait
cat "${dst}server.log"
