#!/bin/bash
set -eo pipefail
set -x

. "$(dirname $0)/../common.sh"

set -u

threads=$1
time=$2
dst="$3"

$hexec l3ep1 \
    iperf3 --server -p 13866 \
    > "${dst}server.log" 2>&1 &
# $! only gives use the pid of sudo.

$hexec l3h1 \
    iperf3 -c 20.20.20.1 -t $time -p 13866 -P $threads --sctp \
    2>&1 | tee "${dst}client.log"

sudo pkill -SIGTERM iperf3
wait
cat "${dst}server.log"
