#!/bin/bash
set -eo pipefail
set -x

. "$(dirname $0)/../common.sh"

set -u

threads=$1
time=$2
dst="$3"

OSE_NGINX_PAYLOAD=${OSE_NGINX_PAYLOAD:-1024}

tmpd=$(mktemp --directory --suffix=$(basename $0))
mkdir -p $tmpd/www
echo "Hello World" > $tmpd/www/hello-world.txt
head --bytes=${OSE_NGINX_PAYLOAD} /dev/urandom > $tmpd/www/head-urandom

echo "
daemon off;  # run in foreground
events {}
pid nginx.pid;
error_log /dev/stderr;
http {
    access_log /dev/stdout;
    client_body_temp_path .;
    proxy_temp_path .;
    fastcgi_temp_path .;
    uwsgi_temp_path .;
    scgi_temp_path .;
    server {
        server_name localhost;
        listen 12865;
        location / {
            root www;
        }
    }
}
" > $tmpd/nginx.conf

$hexec l3ep1 \
    nginx -p $tmpd -c nginx.conf \
    > ${dst}nginx.log \
    &
# $! only gives use the pid of sudo.

$hexec l3h1 \
    curl http://20.20.20.1:12865/hello-world.txt

sudo kill -SIGTERM $(cat $tmpd/nginx.pid)
wait
