# -*- mode: ruby -*-
# vi: set ft=ruby :

workers = (ENV['WORKERS'] || "1").to_i
#box_name = (ENV['VAGRANT_BOX'] || "ubuntu/focal64")
box_name = (ENV['VAGRANT_BOX'] || "sysnet4admin/Ubuntu-k8s")
box_version = "0.7.1"
Vagrant.configure("2") do |config|
  config.vm.box = "#{box_name}"
  config.vm.box_version = "#{box_version}"

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.define "loxilb" do |loxilb|
    loxilb.vm.hostname = 'llb1'
    #loxilb.vm.network "forwarded_port", guest: 55002, host: 5502, protocol: "tcp"
    loxilb.vm.network :private_network, ip: "192.168.80.9", :netmask => "255.255.255.0"
    loxilb.vm.network :private_network, ip: "192.168.90.9", :netmask => "255.255.255.0"
    loxilb.vm.provision :shell, :path => "loxilb.sh"
    loxilb.vm.provider :virtualbox do |vbox|
        vbox.customize ["modifyvm", :id, "--memory", 6000]
        vbox.customize ["modifyvm", :id, "--cpus", 4]
    end
  end


  config.vm.define "master" do |master|
    master.vm.hostname = 'master'
    master.vm.network :private_network, ip: "192.168.80.10", :netmask => "255.255.255.0"
    master.vm.provision :shell, :path => "master.sh"
    master.vm.provider :virtualbox do |vbox|
        vbox.customize ["modifyvm", :id, "--memory", 8192]
        vbox.customize ["modifyvm", :id, "--cpus", 4]
    end
  end

end
