// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BGPPolicyASPathMod b g p policy a s path mod
//
// swagger:model BGPPolicyASPathMod
type BGPPolicyASPathMod struct {

	// as path list
	AsPathList []string `json:"asPathList"`

	// BGP Neighbor IP address
	Name string `json:"name,omitempty"`
}

// Validate validates this b g p policy a s path mod
func (m *BGPPolicyASPathMod) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this b g p policy a s path mod based on context it is used
func (m *BGPPolicyASPathMod) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BGPPolicyASPathMod) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BGPPolicyASPathMod) UnmarshalBinary(b []byte) error {
	var res BGPPolicyASPathMod
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
