// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BGPPolicyNeighborMod b g p policy neighbor mod
//
// swagger:model BGPPolicyNeighborMod
type BGPPolicyNeighborMod struct {

	// BGP Neighbor IP address
	Name string `json:"name,omitempty"`

	// neighbor info list
	NeighborInfoList []string `json:"neighborInfoList"`
}

// Validate validates this b g p policy neighbor mod
func (m *BGPPolicyNeighborMod) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this b g p policy neighbor mod based on context it is used
func (m *BGPPolicyNeighborMod) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BGPPolicyNeighborMod) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BGPPolicyNeighborMod) UnmarshalBinary(b []byte) error {
	var res BGPPolicyNeighborMod
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
