// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EndPointGetEntry end point get entry
//
// swagger:model EndPointGetEntry
type EndPointGetEntry struct {

	// Average delay seen for endpoint
	AvgDelay string `json:"avgDelay,omitempty"`

	// Current state of this endpoint
	CurrState string `json:"currState,omitempty"`

	// Host name
	HostName string `json:"hostName,omitempty"`

	// Number of inactive retries
	InactiveReTries int64 `json:"inactiveReTries,omitempty"`

	// Maximum delay seen for endpoint
	MaxDelay string `json:"maxDelay,omitempty"`

	// Minimum delay seen for endpoint
	MinDelay string `json:"minDelay,omitempty"`

	// Endpoint Identifier
	Name string `json:"name,omitempty"`

	// How frequently to probe in seconds
	ProbeDuration int64 `json:"probeDuration,omitempty"`

	// The l4port to probe on
	ProbePort int64 `json:"probePort,omitempty"`

	// URI for http/https probes
	ProbeReq string `json:"probeReq,omitempty"`

	// Response for http/https probes
	ProbeResp string `json:"probeResp,omitempty"`

	// Type of probe used
	ProbeType string `json:"probeType,omitempty"`
}

// Validate validates this end point get entry
func (m *EndPointGetEntry) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this end point get entry based on context it is used
func (m *EndPointGetEntry) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EndPointGetEntry) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EndPointGetEntry) UnmarshalBinary(b []byte) error {
	var res EndPointGetEntry
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
