// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EndPointHostState end point host state
//
// swagger:model EndPointHostState
type EndPointHostState struct {

	// The end-point port (0 if not applicable)
	EpPort int64 `json:"epPort,omitempty"`

	// The end-point prototype (tcp,udp,sctp,icmp,http(s), empty if not applicable)
	EpProto string `json:"epProto,omitempty"`

	// Host name in CIDR
	HostName string `json:"hostName,omitempty"`

	// Host state string ("green", "yellow", "red" )
	State string `json:"state,omitempty"`
}

// Validate validates this end point host state
func (m *EndPointHostState) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this end point host state based on context it is used
func (m *EndPointHostState) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EndPointHostState) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EndPointHostState) UnmarshalBinary(b []byte) error {
	var res EndPointHostState
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
