// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MessageResponse message response
//
// swagger:model MessageResponse
type MessageResponse struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this message response
func (m *MessageResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this message response based on context it is used
func (m *MessageResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MessageResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MessageResponse) UnmarshalBinary(b []byte) error {
	var res MessageResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
