// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OperState oper state
//
// swagger:model OperState
type OperState struct {

	// Set level to debug,info,error,warning,notice,critical,emergency,alert
	DebugLevel string `json:"debugLevel,omitempty"`
}

// Validate validates this oper state
func (m *OperState) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this oper state based on context it is used
func (m *OperState) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OperState) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OperState) UnmarshalBinary(b []byte) error {
	var res OperState
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
