// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PolicyEntry policy entry
//
// swagger:model PolicyEntry
type PolicyEntry struct {

	// Policy name
	// Required: true
	PolicyIdent *string `json:"policyIdent"`

	// policy info
	PolicyInfo *PolicyEntryPolicyInfo `json:"policyInfo,omitempty"`

	// target object
	// Required: true
	TargetObject *PolicyEntryTargetObject `json:"targetObject"`
}

// Validate validates this policy entry
func (m *PolicyEntry) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePolicyIdent(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePolicyInfo(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTargetObject(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PolicyEntry) validatePolicyIdent(formats strfmt.Registry) error {

	if err := validate.Required("policyIdent", "body", m.PolicyIdent); err != nil {
		return err
	}

	return nil
}

func (m *PolicyEntry) validatePolicyInfo(formats strfmt.Registry) error {
	if swag.IsZero(m.PolicyInfo) { // not required
		return nil
	}

	if m.PolicyInfo != nil {
		if err := m.PolicyInfo.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("policyInfo")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("policyInfo")
			}
			return err
		}
	}

	return nil
}

func (m *PolicyEntry) validateTargetObject(formats strfmt.Registry) error {

	if err := validate.Required("targetObject", "body", m.TargetObject); err != nil {
		return err
	}

	if m.TargetObject != nil {
		if err := m.TargetObject.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("targetObject")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("targetObject")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this policy entry based on the context it is used
func (m *PolicyEntry) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePolicyInfo(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTargetObject(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PolicyEntry) contextValidatePolicyInfo(ctx context.Context, formats strfmt.Registry) error {

	if m.PolicyInfo != nil {
		if err := m.PolicyInfo.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("policyInfo")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("policyInfo")
			}
			return err
		}
	}

	return nil
}

func (m *PolicyEntry) contextValidateTargetObject(ctx context.Context, formats strfmt.Registry) error {

	if m.TargetObject != nil {
		if err := m.TargetObject.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("targetObject")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("targetObject")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PolicyEntry) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PolicyEntry) UnmarshalBinary(b []byte) error {
	var res PolicyEntry
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// PolicyEntryPolicyInfo policy entry policy info
//
// swagger:model PolicyEntryPolicyInfo
type PolicyEntryPolicyInfo struct {

	// Policy color for QoS
	ColorAware bool `json:"colorAware,omitempty"`

	// policy type
	CommittedBlkSize int64 `json:"committedBlkSize,omitempty"`

	// policy type
	CommittedInfoRate int64 `json:"committedInfoRate,omitempty"`

	// policy type
	ExcessBlkSize int64 `json:"excessBlkSize,omitempty"`

	// policy type
	PeakInfoRate int64 `json:"peakInfoRate,omitempty"`

	// policy type(0-TrTCM, 1-SrTCM)
	// Enum: [0 1]
	Type int64 `json:"type,omitempty"`
}

// Validate validates this policy entry policy info
func (m *PolicyEntryPolicyInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var policyEntryPolicyInfoTypeTypePropEnum []interface{}

func init() {
	var res []int64
	if err := json.Unmarshal([]byte(`[0,1]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		policyEntryPolicyInfoTypeTypePropEnum = append(policyEntryPolicyInfoTypeTypePropEnum, v)
	}
}

// prop value enum
func (m *PolicyEntryPolicyInfo) validateTypeEnum(path, location string, value int64) error {
	if err := validate.EnumCase(path, location, value, policyEntryPolicyInfoTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PolicyEntryPolicyInfo) validateType(formats strfmt.Registry) error {
	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("policyInfo"+"."+"type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this policy entry policy info based on context it is used
func (m *PolicyEntryPolicyInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PolicyEntryPolicyInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PolicyEntryPolicyInfo) UnmarshalBinary(b []byte) error {
	var res PolicyEntryPolicyInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// PolicyEntryTargetObject policy entry target object
//
// swagger:model PolicyEntryTargetObject
type PolicyEntryTargetObject struct {

	// Target Attachment
	// Required: true
	Attachment *int64 `json:"attachment"`

	// Target Names
	// Required: true
	PolObjName *string `json:"polObjName"`
}

// Validate validates this policy entry target object
func (m *PolicyEntryTargetObject) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAttachment(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePolObjName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PolicyEntryTargetObject) validateAttachment(formats strfmt.Registry) error {

	if err := validate.Required("targetObject"+"."+"attachment", "body", m.Attachment); err != nil {
		return err
	}

	return nil
}

func (m *PolicyEntryTargetObject) validatePolObjName(formats strfmt.Registry) error {

	if err := validate.Required("targetObject"+"."+"polObjName", "body", m.PolObjName); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this policy entry target object based on context it is used
func (m *PolicyEntryTargetObject) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PolicyEntryTargetObject) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PolicyEntryTargetObject) UnmarshalBinary(b []byte) error {
	var res PolicyEntryTargetObject
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
