// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VxlanEntry vxlan entry
//
// swagger:model VxlanEntry
type VxlanEntry struct {

	// ep intf
	EpIntf string `json:"epIntf,omitempty"`

	// peer IP
	PeerIP []string `json:"peerIP"`

	// vxlan ID
	VxlanID int64 `json:"vxlanID,omitempty"`

	// vxlan name
	VxlanName string `json:"vxlanName,omitempty"`
}

// Validate validates this vxlan entry
func (m *VxlanEntry) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this vxlan entry based on context it is used
func (m *VxlanEntry) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VxlanEntry) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VxlanEntry) UnmarshalBinary(b []byte) error {
	var res VxlanEntry
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
