// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// PutAuthUsersIDOKCode is the HTTP code returned for type PutAuthUsersIDOK
const PutAuthUsersIDOKCode int = 200

/*
PutAuthUsersIDOK OK

swagger:response putAuthUsersIdOK
*/
type PutAuthUsersIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewPutAuthUsersIDOK creates PutAuthUsersIDOK with default headers values
func NewPutAuthUsersIDOK() *PutAuthUsersIDOK {

	return &PutAuthUsersIDOK{}
}

// WithPayload adds the payload to the put auth users Id o k response
func (o *PutAuthUsersIDOK) WithPayload(payload *models.User) *PutAuthUsersIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put auth users Id o k response
func (o *PutAuthUsersIDOK) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutAuthUsersIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutAuthUsersIDBadRequestCode is the HTTP code returned for type PutAuthUsersIDBadRequest
const PutAuthUsersIDBadRequestCode int = 400

/*
PutAuthUsersIDBadRequest Bad Request

swagger:response putAuthUsersIdBadRequest
*/
type PutAuthUsersIDBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewPutAuthUsersIDBadRequest creates PutAuthUsersIDBadRequest with default headers values
func NewPutAuthUsersIDBadRequest() *PutAuthUsersIDBadRequest {

	return &PutAuthUsersIDBadRequest{}
}

// WithPayload adds the payload to the put auth users Id bad request response
func (o *PutAuthUsersIDBadRequest) WithPayload(payload *models.ErrorResponse) *PutAuthUsersIDBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put auth users Id bad request response
func (o *PutAuthUsersIDBadRequest) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutAuthUsersIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutAuthUsersIDInternalServerErrorCode is the HTTP code returned for type PutAuthUsersIDInternalServerError
const PutAuthUsersIDInternalServerErrorCode int = 500

/*
PutAuthUsersIDInternalServerError Internal Server Error

swagger:response putAuthUsersIdInternalServerError
*/
type PutAuthUsersIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewPutAuthUsersIDInternalServerError creates PutAuthUsersIDInternalServerError with default headers values
func NewPutAuthUsersIDInternalServerError() *PutAuthUsersIDInternalServerError {

	return &PutAuthUsersIDInternalServerError{}
}

// WithPayload adds the payload to the put auth users Id internal server error response
func (o *PutAuthUsersIDInternalServerError) WithPayload(payload *models.ErrorResponse) *PutAuthUsersIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put auth users Id internal server error response
func (o *PutAuthUsersIDInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutAuthUsersIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
