name: K3s-Flannel-Sanity-CI
on:
 schedule:
 # Runs "At 11:00 UTC every day-of-week"
 - cron: '0 11 * * *'
 workflow_dispatch:
    inputs:
      testName:
        description: 'Test Run-Name'     
        required: true
        default: 'k3s-flannel'
jobs:
  build:
    name: k3s-flannel-sanity
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update
      - run: |
         echo "KUBECONFIG=--kubeconfig=/etc/rancher/k3s/k3s.yaml" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --disable traefik --disable servicelb --disable-cloud-controller --kubelet-arg cloud-provider=external" K3S_KUBECONFIG_MODE="644" sh -
      - run: |
         sleep 10
         kubectl "${{ env.KUBECONFIG }}" taint nodes --all node.cloudprovider.kubernetes.io/uninitialized=false:NoSchedule-
         sleep 60
         kubectl "${{ env.KUBECONFIG }}" get nodes
         kubectl "${{ env.KUBECONFIG }}" get pods -A
         wget https://github.com/loxilb-io/loxi-ccm/raw/master/manifests/loxi-ccm-k3s.yaml
         kubectl "${{ env.KUBECONFIG }}" apply -f ./loxi-ccm-k3s.yaml
         sleep 60
         kubectl "${{ env.KUBECONFIG }}" get pods -A
      - run: |
         cd cicd/k3s-flannel/
         ./config.sh "${{ env.KUBECONFIG }}"
         ./validation.sh "${{ env.KUBECONFIG }}"
         ./rmconfig.sh "${{ env.KUBECONFIG }}"
         cd -
