name: Liveness-LB-Sanity-CI-Ubuntu-22
on:
  schedule:
  # Runs "At 17:00 UTC every day-of-week"
  - cron: '0 17 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Liveness LB Sanity Ubuntu 22'
  workflow_run:
    workflows: ["Docker-Multi-Arch"]
    types:
      - completed
       
jobs:
  build:
    name: liveness-lb-sanity-ubuntu-22
    runs-on: ubuntu-22.04
    if: github.repository == 'loxilb-io/loxilb'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v2
      - uses: actions/setup-go@v3
        with:
             go-version: '>=1.18.0'
      - run: sudo apt-get update
      - run: sudo apt-get -y install iperf iproute2 nodejs socat ethtool lksctp-tools
      - run: |
             cd cicd/tcplbmon/
             ./config.sh
             ./validation.sh
             ./rmconfig.sh
             cd -
      - run: |
             cd cicd/udplbmon/
             ./config.sh
             ./validation.sh
             ./rmconfig.sh
             cd -
      - run: |
             cd cicd/sctplbmon/
             ./config.sh
             ./validation.sh
             ./rmconfig.sh
             cd -
      - run: |
             cd cicd/tcplbmon6/
             ./config.sh
             ./validation.sh
             ./rmconfig.sh
             cd -
      - run: |
             cd cicd/tcplbepmod/
             ./config.sh
             ./validation.sh
             ./rmconfig.sh
             cd -
      - run: |
             cd cicd/lbtimeout/
             ./config.sh
             ./validation.sh
             ./rmconfig.sh
             cd -
      - run: |
             cd cicd/lb6timeout/
             ./config.sh
             ./validation.sh
             ./rmconfig.sh
             cd -
      - run: |
             cd cicd/httpsep/
             ./config.sh
             ./validation.sh
             ./rmconfig.sh
             cd -
      - run: |
             cd cicd/http2ep/
             ./config.sh
             ./validation.sh
             ./rmconfig.sh
             cd -
